;; expect: #t
(define bv (make-bytevector 3 255))
(bytevector-u8-set! bv 1 7)
(and (bytevector? bv)
     (not (bytevector? "str"))
     (not (string? bv))
     (not (symbol? bv))
     (eq? (bytevector-length bv) 3)
     (eq? (bytevector-u8-ref bv 0) 255)
     (eq? (bytevector-u8-ref bv 1) 7)
     (bytevector=? (bytevector 1 2) (bytevector 1 2))
     (not (bytevector=? (bytevector 1) (bytevector 2)))
     (string=? (utf8->string (bytevector 104 105)) "hi")
     (bytevector=? (string->utf8 "hi") (bytevector 104 105)))
