;; expect: #t
(define (kindof x)
  (case x
    ((1 2 3) 'small)
    ((a b) 'letter)
    ((#\x) 'char)
    (else 'other)))
(define (qq a b ls)
  `(x ,a (y ,b) ,@ls end))
(define (compute)
  (define (g x) (* x 2))
  (define (h x) (+ (g x) 1))
  (h 20))
(define (outer k)
  (define (helper x) (+ x k))
  (helper 5))
(and (eq? (kindof 2) 'small)
     (eq? (kindof 'b) 'letter)
     (eq? (kindof #\x) 'char)
     (eq? (kindof "s") 'other)
     (equal? (qq 1 2 '(3 4)) '(x 1 (y 2) 3 4 end))
     (equal? `(1 ,@'() 2) '(1 2))
     (eq? (compute) 41)
     (eq? (outer 10) 15)
     (eq? (bitwise-and 12 10) 8)
     (eq? (bitwise-ior 12 10) 14)
     (eq? (bitwise-arithmetic-shift-left 3 4) 48)
     (eq? (bitwise-arithmetic-shift-right -8 2) -2)
     (eq? (apply (lambda (f x) (f x)) (list (lambda (v) v) 42)) 42))
