;; expect: #t
(define ht (make-eq-hashtable))
(hashtable-set! ht 'a 1)
(hashtable-set! ht 'b 2)
(hashtable-set! ht 'a 10)
(define hs (make-hashtable string-hash string=?))
(hashtable-set! hs "key" 'val)
;; force growth
(define big (make-eqv-hashtable))
(let loop ((i 0))
  (when (< i 100)
    (hashtable-set! big i (* i i))
    (loop (+ i 1))))
(and (hashtable? ht)
     (eq? (hashtable-ref ht 'a #f) 10)
     (eq? (hashtable-ref ht 'b #f) 2)
     (eq? (hashtable-ref ht 'c 'none) 'none)
     (hashtable-contains? ht 'a)
     (not (hashtable-contains? ht 'zzz))
     (eq? (hashtable-size ht) 2)
     (begin (hashtable-delete! ht 'a)
            (and (not (hashtable-contains? ht 'a))
                 (eq? (hashtable-size ht) 1)))
     (eq? (hashtable-ref hs "key" #f) 'val)
     (eq? (hashtable-size big) 100)
     (eq? (hashtable-ref big 77 #f) 5929)
     (eq? (vector-length (hashtable-keys big)) 100)
     (begin (hashtable-update! big 5 (lambda (v) (+ v 1)) 0)
            (eq? (hashtable-ref big 5 #f) 26)))
