;; expect: #t
(and (equal? (list 1 2 3) '(1 2 3))
     (eq? (length '(a b c)) 3)
     (equal? (append '(1 2) '(3 4)) '(1 2 3 4))
     (equal? (reverse '(1 2 3)) '(3 2 1))
     (equal? (map (lambda (x) (* x x)) '(1 2 3)) '(1 4 9))
     (equal? (memq 'b '(a b c)) '(b c))
     (equal? (assq 'y '((x 1) (y 2))) '(y 2))
     (let ((sum 0))
       (for-each (lambda (x) (set! sum (+ sum x))) '(1 2 3 4))
       (eq? sum 10)))
