;; expect: #t
(and (let-values (((q r) (values 3 2))
                  ((x . more) (values 1 4 5)))
       (and (eq? (+ q (+ r x)) 6) (equal? more '(4 5))))
     (let*-values (((a) (values 1)) ((b) (values (+ a 10))))
       (eq? b 11))
     (eq? (assert 42) 42)
     (eq? (cons* 5) 5)
     (equal? (cons* 1 2 '(3 4)) '(1 2 3 4))
     (equal? (map + '(1 2) '(10 20)) '(11 22))
     (equal? (map (lambda (a b c) (+ a (+ b c))) '(1) '(2) '(3)) '(6))
     (let ((acc 0))
       (for-each (lambda (a b) (set! acc (+ acc (* a b)))) '(1 2) '(3 4))
       (eq? acc 11)))
