;; expect: #t
(define op (open-output-string))
(display 'hello op)
(display " " op)
(write "wo\"rld" op)
(define ip (open-input-string "42 (a b) end"))
(and (port? op)
     (output-port? op)
     (string=? (get-output-string op) "hello \"wo\\\"rld\"")
     (input-port? ip)
     (= (read ip) 42)
     (equal? (read ip) '(a b))
     (eq? (read ip) 'end)
     (eof-object? (read ip))
     (string=? (with-output-to-string (lambda () (display (+ 1 2)))) "3")
     (let ((p (open-input-string "xy")))
       (and (char=? (peek-char p) #\x)
            (char=? (read-char p) #\x)
            (char=? (read-char p) #\y)
            (eof-object? (read-char p))))
     (string=? (number->string 12345) "12345")
     (string=? (number->string (* 1000000 1000000)) "1000000000000")
     (string=? (number->string 2.5) "2.5")
     (= (string->number "123") 123)
     (= (string->number "-4.5") (- 0 4.5))
     (= (string->number "123456789012345678") 123456789012345678)
     (not (string->number "12abc"))
     (not (string->number "")))
