;; expect: #t
(and (char? #\a)
     (not (char? 65))
     (number? 65)
     (not (number? #\a))
     (eq? (char->integer #\A) 65)
     (eq? (integer->char 66) #\B)
     (boolean? #f)
     (boolean? #t)
     (not (boolean? 0))
     (procedure? (lambda (x) x))
     (not (procedure? 5))
     (string? "s")
     (not (string? 's)))
