;; expect: #t
(define-record-type point (fields x (mutable y)))
(define-record-type (box mk-box box?) (fields (mutable v box-val box-val!)))
(define p (make-point 3 4))
(define b (mk-box 'stuff))
(point-y-set! p 40)
(box-val! b 'other)
(and (point? p)
     (not (point? b))
     (not (box? p))
     (box? b)
     (eq? (point-x p) 3)
     (eq? (point-y p) 40)
     (eq? (box-val b) 'other)
     (not (point? 5))
     (not (point? '(1 . 2))))
