;; expect: #t
;; Read actual resident instance data; skipping an upload must not hide stale bytes.
(import (rnrs) (web js) (gfx gl) (gfx fx) (gfx mat) (gfx mesh)
        (web reactive) (gfx scene))
(js-eval "globalThis.__resident = []; globalThis.__gllog = []; globalThis.__idx = []; globalThis.__draws = []; globalThis.__mockcanvas = { width:640, height:480, addEventListener(k,f){}, getContext(kind) { const log = globalThis.__gllog; const push = (...a) => log.push(a.join(':')); return { VERTEX_SHADER:'VS', FRAGMENT_SHADER:'FS', COMPILE_STATUS:'CS', LINK_STATUS:'LS', COLOR_BUFFER_BIT:16384, DEPTH_BUFFER_BIT:256, ARRAY_BUFFER:'AB', DYNAMIC_DRAW:'DD', FLOAT:'F', POINTS:'PTS', LINES:'LNS', TRIANGLES:'TRI', TRIANGLE_STRIP:'STRIP', DEPTH_TEST:'DT', ELEMENT_ARRAY_BUFFER:'EAB', UNSIGNED_SHORT:'US', UNSIGNED_INT:'UI', BLEND:'BL', SRC_ALPHA:'SA', ONE:'ONE', ONE_MINUS_SRC_ALPHA:'OMSA', createShader(k){ return {kind:k} }, shaderSource(s,src){}, compileShader(s){}, getShaderParameter(){ return true }, createProgram(){ return {id:'P'+(this._p=(this._p||0)+1)} }, attachShader(p,s){}, linkProgram(p){}, getProgramParameter(){ return true }, bindAttribLocation(p,i,n){ push('bindAttrib', i, n) }, createVertexArray(){ return {id:'V'+(this._v=(this._v||0)+1)} }, bindVertexArray(v){this.vao=v}, createBuffer(){ return {id:'B'+(this._b=(this._b||0)+1)} }, getUniformLocation(p,n){ return {id:'U:'+n} }, UNIFORM_BUFFER:'UBUF', getUniformBlockIndex(pr,n){ return 'I:' + n }, uniformBlockBinding(pr,i,b){ push('ubb', pr.id, i, b) }, bindBufferBase(t,b,buf){ push('bbb', t, b, buf ? buf.id : 'null') }, bufferSubData(t,o,arr){ push('subData', t, arr.length) }, enable(c){ push('gEnable', c) }, disable(c){ push('gDisable', c) }, blendFunc(a,b){ push('blendFunc', a, b) }, clearColor(...a){ push('clearColor', ...a.map(x=>x.toFixed(2))) }, clear(bits){ push('clear', bits) }, useProgram(p){ push('useProgram', p.id) }, bindBuffer(t,b){this.bound=b; push(t==='EAB'?'bindIndex':'bindBuffer', b.id) }, bufferData(t,arr,u){if(typeof arr!=='number'){this.bound.values=Array.from(arr);this.bound.words=Array.from(new Uint32Array(arr.buffer,arr.byteOffset,arr.byteLength/4));} if (t==='EAB' && typeof arr !== 'number') { globalThis.__idx.push({v:Array.from(arr), w:arr.BYTES_PER_ELEMENT}); } push('bufferData', typeof arr === 'number' ? 'size' + arr : arr.length) }, enableVertexAttribArray(l){ push('enable', l) }, vertexAttribPointer(...a){if(a[4]===80)this.vao.instances=this.bound; push('attrib', a.join(',')) }, uniform1f(loc,x){ push('uniform1f', loc.id, x.toFixed(2)) }, uniform2f(loc,x,y){ push('uniform2f', loc.id, x.toFixed(2), y.toFixed(2)) }, uniform3f(loc,x,y,z){ push('uniform3f', loc.id, x.toFixed(2), y.toFixed(2), z.toFixed(2)) }, uniform4f(loc,...a){ push('uniform4f', loc.id, a.map(x=>x.toFixed(1)).join(',')) }, uniformMatrix4fv(loc,tr,arr){ push('uniformMat4', loc.id, arr.length, arr[0].toFixed(2), arr[12].toFixed(2)) }, uniform1i(loc,v){ push('uniform1i', loc.id, v) }, activeTexture(u){ push('activeTexture', u) }, bindTexture(t,tex){ push('bindTexture', tex ? tex.id : 'null') }, createTexture(){ return {id:'T'+(this._t=(this._t||0)+1)} }, texParameteri(){}, TEXTURE0:33984, TEXTURE_2D:'T2D', TEXTURE_CUBE_MAP:'TCM', drawArrays(m,f,c){ push('draw', m, f, c) }, drawElements(m,c,t,o){ globalThis.__draws.push({n:c, t:t, inst:0, m:m}); push('drawElements', m, c, t) }, depthMask(b){ push('depthMask', b?1:0) }, vertexAttribDivisor(l,d){ if (d > 0) push('divisor', l, d) }, drawElementsInstanced(m,c,t,o,n){globalThis.__resident.push({values:this.vao.instances.values.slice(0,n*20),words:this.vao.instances.words.slice(0,n*20)}); globalThis.__draws.push({n:c, t:t, inst:n, m:m}); push('drawInst', m, c, n) }, viewport(...a){ push('viewport', a.join(',')) } } } }")
(define (check name ok) (unless ok (error 'scene-resident-output name)))
(fx-init! (js-get (js-global) "__mockcanvas"))
(define lens (signal 0.9))
(define near (signal 0.1))
(define far (signal 60.0))
(define red (signal 0.25))
(define turn (signal 0.0))
(define parent-x (signal 0.0))
(define sc
  (sgl (camera (@ (fov ,(signal-ref lens)) (position 0.0 0.0 10.0)
                  (look-at 0.0 0.0 0.0) (near ,(signal-ref near)) (far ,(signal-ref far))))
       (light (@ (direction 0.0 1.0 0.0) (ambient 0.25)))
       (group (@ (position-x ,(signal-ref parent-x)))
         (mesh (@ (geometry (box 1 1 1)) (position -1.0 0.0 0.0)
                  (color-r ,(signal-ref red)) (rotation-y ,(signal-ref turn))))
         (mesh (@ (geometry (box 1 1 1)) (position 1.0 0.0 -10.0)))
         (mesh (@ (geometry (box 1 1 1)) (position 0.0 0.0 -40.0))))))
(define (frame)
  (js-eval "__gllog.length=0;__draws.length=0;__resident.length=0")
  (cmd-begin!) (sgl-draw! sc) (cmd-flush!))
(define (uploads) (js->number (js-eval "__gllog.filter(s=>s.startsWith('bufferData:')).length")))
(define (instances) (js->number (js-eval "__draws.reduce((s,d)=>s+d.inst,0)")))
(define (snapshot) (js->string (js-eval "JSON.stringify(__resident.map(r=>r.words))")))
(define (value i k) (js->number (js-eval (string-append "__resident[0].values[" (number->string (+ (* i 20) k)) "]"))))
(frame)
(check "initial three instances" (= (instances) 3))
(define initial (snapshot))
(frame)
(check "unchanged camera retains GPU bytes" (and (= (uploads) 0) (string=? initial (snapshot))))
(do ((i 1 (+ i 1))) ((> i 8))
  (signal-set! lens (+ 0.9 (* 0.001 i))) (frame)
  (check "changed camera, same output, no upload" (and (= (instances) 3) (= (uploads) 0) (string=? initial (snapshot)))))
(signal-set! red 0.75) (frame)
(check "same nodes with new colour must upload" (and (= (uploads) 1) (= (value 0 16) 0.75)))
(define coloured (snapshot))
(signal-set! turn 0.25) (frame)
(check "same nodes with new transform must upload" (and (= (uploads) 1) (not (string=? coloured (snapshot)))))
(signal-set! parent-x 0.25) (frame)
(check "ancestor transform invalidates resident bytes" (and (= (uploads) 1) (= (value 0 12) -0.75) (= (value 1 12) 1.25)))
(signal-set! far 30.0) (frame)
(check "shrinking visible count updates the draw" (and (= (instances) 2) (= (uploads) 1)))
(define short (snapshot))
(signal-set! lens 0.91) (frame)
(check "smaller identical result remains resident" (and (= (instances) 2) (= (uploads) 0) (string=? short (snapshot))))
(signal-set! far 15.0) (frame)
(check "first singleton owns its transform" (and (= (instances) 1) (= (uploads) 1) (= (value 0 12) -0.75)))
(signal-set! near 15.0) (signal-set! far 30.0) (frame)
(check "same count with different identity must upload" (and (= (instances) 1) (= (uploads) 1) (= (value 0 12) 1.25)))
(signal-set! near 25.0) (signal-set! far 60.0) (frame)
(check "a different visible identity uses its own bytes" (and (= (instances) 1) (= (uploads) 1) (= (value 0 14) -40.0)))
(signal-set! near 55.0) (frame)
(check "empty result draws nothing" (and (= (instances) 0) (= (uploads) 0)))
(signal-set! near 0.1) (frame)
(check "empty to nonempty refreshes the complete buffer" (and (= (instances) 3) (= (uploads) 1) (= (value 0 16) 0.75)))
(frame)
(check "newly resident result can be reused" (and (= (instances) 3) (= (uploads) 0)))
#t
