;; expect: #t
(and (string=? (substring "hello world" 6 11) "world")
     (string=? (string-copy "abc") "abc")
     (string=? (string-append) "")
     (string=? (string-append "a" "b" "c" "d") "abcd")
     (string=? (string #\G #\o) "Go")
     (string=? (make-string 3 #\z) "zzz")
     (string<? "abc" "abd")
     (string<? "ab" "abc")
     (string>? "b" "a")
     (string<=? "same" "same")
     (string>=? "same" "same")
     (char=? #\a #\a)
     (char<? #\a #\b)
     (char>=? #\b #\a)
     (char=? (char-upcase #\q) #\Q)
     (char=? (char-downcase #\Q) #\q)
     (char-alphabetic? #\k)
     (not (char-alphabetic? #\5))
     (char-numeric? #\7)
     (char-whitespace? #\space)
     (string=? (string-upcase "mixed Case1") "MIXED CASE1")
     (string=? (string-downcase "MIXED Case1") "mixed case1")
     (string=? (string-map (lambda (c) (char-upcase c)) "abc") "ABC")
     (let ((n 0))
       (string-for-each (lambda (c) (set! n (+ n (char->integer c)))) "AB")
       (= n 131)))
