;; expect: #t
(define v (make-vector 3 7))
(vector-set! v 1 42)
(and (vector? v)
     (not (vector? '(1)))
     (eq? (vector-length v) 3)
     (eq? (vector-ref v 0) 7)
     (eq? (vector-ref v 1) 42)
     (equal? (vector->list (vector 1 2 3)) '(1 2 3))
     (equal? (vector->list (list->vector '(a b))) '(a b))
     (equal? (vector->list '#(1 (2 3) x)) '(1 (2 3) x))
     (equal? (vector->list (vector-map (lambda (x) (* x x)) (vector 1 2 3)))
             '(1 4 9))
     (let ((w (make-vector 2 0)))
       (vector-fill! w 9)
       (eq? (+ (vector-ref w 0) (vector-ref w 1)) 18)))
