;; intro.html — "Beyond Files", a 2D animated introduction, authored
;; in Scheme and rendered by Goeteia.
;;
;; The generator half writes the page: the stage, the player controls
;; and the chapter list (which doubles as the no-script transcript).
;; The browser half is one define-wasm-js mount: every frame of the
;; film is drawn on a <canvas> by Scheme compiled to WebAssembly, with
;; a JS twin generated from the same source for engines without WasmGC.
;; Scene kickers and titles are read back from the chapter buttons, so
;; the chapter list below is the single source of the names.
(import (web html) (web css) (chrome))

;; ---- chapters: (kicker title summary) -------------------------------
(define chapters
  '(("" "Beyond files"
     "Markdown and plain source files are great for humans to write in. As the memory and engineering substrate for multi-agent systems, they hit five systemic walls.")
    ("WALL 1 / 5" "Silent write errors"
     "Plain text has zero structural validation on write: a botched patch quietly drops a section. Reading back after every write to verify doubles the token burn.")
    ("WALL 2 / 5" "Concurrent overwrites & environment collisions"
     "No block-level isolation: parallel writers blindly overwrite each other, and a shared working directory corrupts each other's execution state.")
    ("WALL 3 / 5" "The token black hole"
     "Files grow monotonically and the file is the unit of addressing, so needing one rule or function means reading the whole monolith.")
    ("WALL 4 / 5" "Runaway long-tail topology"
     "A file-based knowledge base decays into thousands of atomic notes and a handful of massive files; splitting them by hand shatters the logical flow.")
    ("WALL 5 / 5" "Drifting indexes"
     "Vector indexes and line-number maps are detached from the text; when a paragraph moves they go stale silently, feeding hallucinations while semantic breaks stay invisible to Git.")
    ("THE SHIFT" "Stop organizing content by files"
     "Blocks store both documentation and source code. Files are still projected when needed, but a file boundary no longer decides what is read, written, or run.")
    ("FEATURE 1 / 7" "A minimal query surface for agents"
     "outline, search, refs and batch answer in dense S-expressions, one item per line, with the token footprint visible before reading.")
    ("FEATURE 2 / 7" "One unified graph across docs and code"
     "Design sections, source files, macros, functions and decision records are equal blocks with stable IDs, joined by typed, directed edges.")
    ("FEATURE 3 / 7" "Global backlinks at near-zero cost"
     "One refs query shows every mention; search reads only the answering block: 15% of the tokens of reading the full document, and a corpus outline is 6% of its raw Markdown.")
    ("FEATURE 4 / 7" "Deterministic context assembly"
     "Datalog-style queries over in-memory facts, and a budget-bounded context compiler: must-read constraints, then evidence, with every exclusion explained.")
    ("FEATURE 5 / 7" "Human–agent symbiosis in the IDE"
     "A semantic lens above every definition, renames that name the docs they left behind, agent drafts reviewed with the whole IDE, and precision test runs.")
    ("FEATURE 6 / 7" "Zero-conflict workspaces & isolated execution"
     "Private scratchpads with their own environments; commit is atomic with baseline optimistic locking, and a stale baseline is refused with everything needed to merge.")
    ("FEATURE 7 / 7" "A Lisp machine: a living knowledge base"
     "Scheme blocks evaluate in place inside quota-bound sandboxes, and at any historical cut of the log, reproducibly.")
    ("" "Blocks, not files"
     "One living graph for docs, code, tests and decisions — shared by humans and agents.")))

;; ---- the page's browser half ------------------------------------------
(define-wasm-js (film "intro.wasm" "intro.js")
  (import (rnrs) (web js) (web dom) (gfx mat))

  ;; ---------------------------------------------------------------
  ;; math the prelude leaves out
  (define (sin x) (flsin (exact->inexact x)))
  (define (cos x) (flcos (exact->inexact x)))
  (define js-atan2 (js-get (js-get (js-global) "Math") "atan2"))
  (define (atan y x) (js->number (js-call js-atan2 (js-undefined) y x)))
  (define (mod a b) (let ((r (remainder a b))) (if (< r 0) (+ r b) r)))
  (define (even? n) (= 0 (mod n 2)))
  (define (hex n)
    (let loop ((n n) (acc ""))
      (let ((acc (string-append (string (string-ref "0123456789abcdef" (mod n 16))) acc)))
        (if (< n 16) acc (loop (quotient n 16) acc)))))

  ;; ---------------------------------------------------------------
  ;; stage & drawing primitives
  (define W 1600)
  (define H 900)
  (define SANS "Inter, system-ui, -apple-system, \"Segoe UI\", sans-serif")
  (define MONO "ui-monospace, \"SF Mono\", Menlo, Consolas, monospace")

  (define BG "#0a0f1f") (define PANEL "#121a33") (define PANEL2 "#17213f")
  (define LINE "#2a3659") (define INK "#e8ecf8") (define DIM "#8e98bd")
  (define FAINT "#4b5680") (define AZURE "#4f8ff7") (define RED "#ff6b6b")
  (define GREEN "#3ddc97") (define AMBER "#ffb547") (define VIOLET "#a78bfa")
  (define TEAL "#2dd4bf") (define PINK "#f472b6")

  (define cv (get-element-by-id "stage"))
  (define ctx (js-method cv "getContext" "2d"))
  (define dash-arr (js-eval "[7,6]"))
  (define no-dash (js-eval "[]"))

  (define (clamp01 x) (cond ((< x 0) 0.0) ((> x 1) 1.0) (else x)))
  (define (ramp t a b) (clamp01 (/ (- t a) (- b a))))
  (define (ez p) (* p p (- 3 (* 2 p))))
  (define (eo p) (let ((q (- 1 p))) (- 1 (* q q q))))
  (define (eb p)                          ; ease-out with overshoot
    (let ((q (- p 1))) (+ 1 (* q q (+ (* 2.7 q) 1.7)))))
  (define (rz t a b) (ez (ramp t a b)))
  (define (ro t a b) (eo (ramp t a b)))
  (define (lerp a b p) (+ a (* (- b a) p)))
  (define (between? t a b) (and (>= t a) (< t b)))
  (define (pulse t f) (+ 0.5 (* 0.5 (sin (* t f)))))
  (define (int x) (exact (floor x)))

  (define (fmt n)                         ; 38400 -> "38,400"
    (let loop ((s (number->string (int n))) (acc ""))
      (if (<= (string-length s) 3)
          (string-append s acc)
          (let ((k (- (string-length s) 3)))
            (loop (substring s 0 k)
                  (string-append "," (substring s k (string-length s)) acc))))))

  (define (typed s p)
    (substring s 0 (int (* (clamp01 p) (string-length s)))))

  ;; cached context state (invalidated on restore and each frame)
  (define cur-font "") (define cur-align "") (define cur-a 1.0)
  (define (reset-cache!) (set! cur-font "") (set! cur-align ""))

  (define (fill! c) (js-set! ctx "fillStyle" c))
  (define (stroke! c) (js-set! ctx "strokeStyle" c))
  (define (lw! w) (js-set! ctx "lineWidth" w))
  (define (dash! on) (js-method ctx "setLineDash" (if on dash-arr no-dash)))

  (define (with-a a thunk)
    (let ((old cur-a))
      (set! cur-a (* old (clamp01 a)))
      (js-set! ctx "globalAlpha" cur-a)
      (when (> cur-a 0.004) (thunk))
      (set! cur-a old)
      (js-set! ctx "globalAlpha" old)))
  (define-syntax fade
    (syntax-rules () ((_ a body ...) (with-a a (lambda () body ...)))))

  (define (with-xf x y s thunk)
    (js-method ctx "save")
    (js-method ctx "translate" x y)
    (js-method ctx "scale" s s)
    (thunk)
    (js-method ctx "restore")
    (reset-cache!))
  (define-syntax at
    (syntax-rules () ((_ x y s body ...) (with-xf x y s (lambda () body ...)))))

  (define (font! px weight mono?)
    (let ((f (string-append (number->string weight) " "
                            (number->string (int px)) "px "
                            (if mono? MONO SANS))))
      (unless (string=? f cur-font)
        (set! cur-font f)
        (js-set! ctx "font" f))))
  (define (align! a)
    (unless (string=? a cur-align)
      (set! cur-align a)
      (js-set! ctx "textAlign" a)))

  ;; (txt s x y px color [align weight mono?])
  (define (txt s x y px color . o)
    (let* ((align (if (pair? o) (car o) "left"))
           (o2 (if (pair? o) (cdr o) '()))
           (weight (if (pair? o2) (car o2) 400))
           (mono (and (pair? o2) (pair? (cdr o2)) (cadr o2))))
      (font! px weight mono)
      (align! align)
      (fill! color)
      (js-method ctx "fillText" s x y)))
  (define (mtxt s x y px color . o)       ; monospace
    (txt s x y px color (if (pair? o) (car o) "left")
         (if (and (pair? o) (pair? (cdr o))) (cadr o) 400) #t))
  (define (text-w s px weight mono?)
    (font! px weight mono?)
    (js->number (js-get (js-method ctx "measureText" s) "width")))

  (define (rr-path x y w h r)
    (js-method ctx "beginPath")
    (js-method ctx "roundRect" x y w h (min r (min (/ w 2) (/ h 2)))))
  (define (box x y w h r fillc strokec . o)
    (when (and (> w 0.5) (> h 0.5))
      (rr-path x y w h r)
      (when fillc (fill! fillc) (js-method ctx "fill"))
      (when strokec
        (stroke! strokec)
        (lw! (if (pair? o) (car o) 1.5))
        (js-method ctx "stroke"))))
  (define (dbox x y w h r strokec)        ; dashed outline
    (dash! #t) (box x y w h r #f strokec 2) (dash! #f))
  (define (rect x y w h c)
    (fill! c) (js-method ctx "fillRect" x y w h))
  (define (circle x y r fillc strokec . o)
    (js-method ctx "beginPath")
    (js-method ctx "arc" x y (max r 0.1) 0 6.2832)
    (when fillc (fill! fillc) (js-method ctx "fill"))
    (when strokec
      (stroke! strokec) (lw! (if (pair? o) (car o) 2)) (js-method ctx "stroke")))
  (define (line x1 y1 x2 y2 c w)
    (js-method ctx "beginPath")
    (js-method ctx "moveTo" x1 y1)
    (js-method ctx "lineTo" x2 y2)
    (stroke! c) (lw! w)
    (js-method ctx "stroke"))
  (define (poly pts c w)                  ; pts: list of (x . y)
    (unless (null? pts)
      (js-method ctx "beginPath")
      (js-method ctx "moveTo" (caar pts) (cdar pts))
      (for-each (lambda (p) (js-method ctx "lineTo" (car p) (cdr p))) (cdr pts))
      (stroke! c) (lw! w)
      (js-method ctx "stroke")))
  ;; arrow drawn to progress p (0..1) of the way from 1 to 2
  (define (arrow x1 y1 x2 y2 c w . o)
    (let* ((p (if (pair? o) (car o) 1.0))
           (dashed (and (pair? o) (pair? (cdr o)) (cadr o)))
           (ex (lerp x1 x2 p)) (ey (lerp y1 y2 p))
           (a (atan (- y2 y1) (- x2 x1)))
           (hl (+ 8 (* 2 w))))
      (when (> p 0.01)
        (when dashed (dash! #t))
        (line x1 y1 ex ey c w)
        (when dashed (dash! #f))
        (when (> p 0.12)
          (js-method ctx "beginPath")
          (js-method ctx "moveTo" ex ey)
          (js-method ctx "lineTo" (- ex (* hl (cos (- a 0.45)))) (- ey (* hl (sin (- a 0.45)))))
          (js-method ctx "lineTo" (- ex (* hl (cos (+ a 0.45)))) (- ey (* hl (sin (+ a 0.45)))))
          (js-method ctx "closePath")
          (fill! c) (js-method ctx "fill")))))
  (define (check x y s c)
    (poly (list (cons (- x s) y) (cons (- x (* 0.3 s)) (+ y (* 0.7 s)))
                (cons (+ x s) (- y (* 0.8 s))))
          c (max 2 (* 0.35 s))))
  (define (cross x y s c)
    (line (- x s) (- y s) (+ x s) (+ y s) c (max 2 (* 0.35 s)))
    (line (- x s) (+ y s) (+ x s) (- y s) c (max 2 (* 0.35 s))))

  ;; a pill: outline + mono label, centred vertically on y; returns width
  (define (chip s x y c . o)
    (let* ((px (if (pair? o) (car o) 15))
           (filled (and (pair? o) (pair? (cdr o)) (cadr o)))
           (w (+ (text-w s px 500 #t) (* 1.4 px)))
           (h (* 1.9 px)))
      (box x (- y (/ h 2)) w h (/ h 2) (if filled c PANEL) c 1.5)
      (mtxt s (+ x (* 0.7 px)) (+ y 1) px (if filled BG c) "left" 500)
      w))
  (define (chip-c s x y c . o)             ; centred on x
    (let ((px (if (pair? o) (car o) 15)))
      (chip s (- x (/ (+ (text-w s px 500 #t) (* 1.4 px)) 2)) y c px
            (and (pair? o) (pair? (cdr o)) (cadr o)))))

  ;; pseudo text lines inside a card
  (define LENS '#(0.92 0.74 0.86 0.58 0.95 0.68 0.81 0.47 0.9 0.63 0.77 0.52))
  (define (lines x y w n step c . o)
    (let ((off (if (pair? o) (car o) 0)))
      (do ((i 0 (+ i 1))) ((>= i n))
        (box x (+ y (* i step)) (* w (vector-ref LENS (mod (+ i off) 12))) 7 3.5 c #f))))

  (define (doc-card x y w h name accent)
    (box x y w h 12 PANEL2 LINE 1.5)
    (box x y w 38 12 "#1c2850" #f)
    (circle (+ x 20) (+ y 19) 5 accent #f)
    (mtxt name (+ x 34) (+ y 20) 15 DIM))

  ;; avatars: an agent is a little robot, a human a bust
  (define (avatar x y r c kind label)
    (if (eq? kind 'human)
        (begin
          (circle x (- y (* 0.25 r)) (* 0.42 r) PANEL c 3)
          (js-method ctx "beginPath")
          (js-method ctx "arc" x (+ y (* 0.95 r)) (* 0.75 r) 3.5 5.93)
          (stroke! c) (lw! 3) (js-method ctx "stroke"))
        (begin
          (line x (- y r) x (- y (* 1.35 r)) c 3)
          (circle x (- y (* 1.42 r)) 4 c #f)
          (box (- x r) (- y (* 0.85 r)) (* 2 r) (* 1.7 r) (* 0.45 r) PANEL c 3)
          (rect (- x (* 0.45 r)) (- y (* 0.25 r)) (* 0.25 r) (* 0.3 r) c)
          (rect (+ x (* 0.2 r)) (- y (* 0.25 r)) (* 0.25 r) (* 0.3 r) c)))
    (when label (mtxt label x (+ y r 22) 15 c "center" 500)))

  (define (bar x y w h frac c)
    (box x y w h (/ h 2) "#0e1530" LINE 1)
    (box x y (* w (clamp01 frac)) h (/ h 2) c #f))

  ;; a graph node: type tag, label, stable id
  (define (node x y w h c tag label id)
    (box (- x (/ w 2)) (- y (/ h 2)) w h 10 PANEL2 c 2)
    (mtxt tag (- x (/ w 2) -12) (- y 12) 12 c "left" 600)
    (txt label (- x (/ w 2) -12) (+ y 12) 17 INK "left" 600)
    (when id (mtxt id (+ x (/ w 2) -10) (- y 12) 12 FAINT "right")))

  (define (bubble x y s c)                ; speech bubble centred on x
    (let ((w (+ (text-w s 18 500 #f) 32)))
      (box (- x (/ w 2)) (- y 22) w 44 14 PANEL c 2)
      (txt s x (+ y 1) 18 c "center" 500)))

  (define (toast s x y c)
    (let ((w (+ (text-w s 18 600 #f) 36)))
      (box (- x (/ w 2)) (- y 21) w 42 21 c #f)
      (txt s x (+ y 1) 18 BG "center" 600)))

  ;; background: gradient + dot grid, rendered once offscreen
  (define bg
    (let* ((c (js-method (document) "createElement" "canvas"))
           (g (js-method c "getContext" "2d")))
      (js-set! c "width" W) (js-set! c "height" H)
      (let ((gr (js-method g "createRadialGradient" 800 380 60 800 450 1000)))
        (js-method gr "addColorStop" 0 "#131c3a")
        (js-method gr "addColorStop" 1 "#070b17")
        (js-set! g "fillStyle" gr)
        (js-method g "fillRect" 0 0 W H))
      (js-set! g "fillStyle" "rgba(120,140,200,0.10)")
      (do ((y 20 (+ y 40))) ((> y H))
        (do ((x 20 (+ x 40))) ((> x W))
          (js-method g "fillRect" x y 2 2)))
      c))

  ;; deterministic pseudo-random numbers
  (define seed 12345)
  (define (rnd)
    (set! seed (mod (+ (* seed 75) 74) 65537))
    (/ seed 65537.0))

  ;; ---------------------------------------------------------------
  ;; scenes

  ;; 0 -- intro
  (define (s-intro t)
    (fade (ro t 0.2 1.2)
      (txt "Files are great for humans to write in." 800 190 54 INK "center" 700))
    (fade (ro t 4.2 5.2)
      (txt "As the substrate for multi-agent systems, they hit five walls."
           800 256 30 RED "center" 500))
    (let ((names '#("design.md" "store.py" "macros.ss"))
          (accs (vector AZURE VIOLET GREEN)))
      (do ((i 0 (+ i 1))) ((= i 3))
        (let* ((p (clamp01 (ramp t (+ 0.6 (* 0.3 i)) (+ 1.3 (* 0.3 i)))))
               (x (+ 520 (* 280 i))) (y 480)
               (shake (if (> t 5) (* 3 (sin (* t (+ 31 (* 7 i))))) 0)))
          (fade p
            (at (+ x shake) y (* 0.6 (+ 0.4 (* 0.6 (eb p))))
              (doc-card -160 -200 320 400 (vector-ref names i) (vector-ref accs i))
              (lines -130 -130 260 (int (* 12 (ramp t (+ 1.4 (* 0.2 i)) 4))) 26 FAINT i)
              (fade (rz t 5 5.8)
                (poly '((-40 . -200) (-10 . -120) (-50 . -40) (0 . 40) (-30 . 120) (10 . 200))
                      RED 5)))))))
    (fade (ro t 1.4 2.2) (avatar 250 500 34 AMBER 'human "human"))
    (let ((pts '#((1330 . 380) (1420 . 540) (1310 . 690) (800 . 750) (1450 . 720))))
      (do ((i 0 (+ i 1))) ((= i 5))
        (let* ((p (ro t (+ 3.6 (* 0.25 i)) (+ 4.3 (* 0.25 i))))
               (q (vector-ref pts i)))
          (fade p
            (avatar (car q) (cdr q) 26 (if (even? i) AZURE VIOLET) 'agent #f)
            (fade (* 0.5 (pulse t (+ 7 i)))
              (arrow (car q) (cdr q) (lerp (car q) 800 0.55) (lerp (cdr q) 480 0.55)
                     (if (even? i) AZURE VIOLET) 2 1.0 #t)))))))

  ;; 1 -- silent write errors
  (define (s-wall1 t)
    (let* ((x 200) (y 180) (w 440)
           (k (ro t 3.2 4.2))
           (heads '#("§1 Overview" "§2 Write path" "§3 Recovery" "§4 Open questions"))
           (cols (vector AZURE VIOLET TEAL AMBER)))
      (doc-card x y w 580 "design.md" AZURE)
      (do ((i 0 (+ i 1))) ((= i 4))
        (let* ((sy (+ y 58 (* i 128) (if (> i 2) (* -128 k) 0)))
               (a (if (= i 2) (- 1 k) 1)))
          (fade a
            (at 0 sy 1
              (js-method ctx "scale" 1 (if (= i 2) (max 0.01 (- 1 k)) 1))
              (txt (vector-ref heads i) (+ x 28) 12 19 (vector-ref cols i) "left" 700)
              (lines (+ x 28) 34 (- w 60) 3 24 FAINT i)))))
      ;; the patch travelling from the agent
      (fade (* (ramp t 1.2 1.6) (- 1 (ramp t 2.9 3.2)))
        (let* ((p (rz t 1.4 3.0)) (px (lerp 1100 420 p)) (py (lerp 300 470 p)))
          (box (- px 95) (- py 30) 190 60 8 PANEL VIOLET 2)
          (mtxt "@@ -41,9 +41,2 @@" px (- py 6) 14 VIOLET "center")
          (mtxt "- ### Recovery ..." px (+ py 16) 13 RED "center")))
      (avatar 1180 300 38 AZURE 'agent "agent-a")
      (fade (ro t 3.9 4.4) (toast "✓ write ok · 0 errors" 1180 412 GREEN))
      (fade (ro t 4.9 5.6)
        (dbox 680 405 330 84 10 RED)
        (txt "§3 Recovery" 706 436 19 RED "left" 700)
        (txt "silently dropped — nothing threw" 706 466 17 RED)
        (arrow 690 447 (+ x w -4) 447 RED 2 (ro t 5.2 5.8)))
      ;; verify-by-rereading doubles the bill
      (fade (ro t 7.2 7.8)
        (box 900 540 560 210 14 PANEL LINE)
        (txt "tokens per edit" 930 578 19 DIM "left" 600)
        (txt "write" 930 626 17 INK)
        (bar 1060 612 240 26 (ro t 7.6 8.3) AZURE)
        (txt "read back to verify" 930 684 17 INK)
        (bar 1110 670 240 26 (ro t 8.6 9.6) AMBER)
        (fade (ro t 9.6 10.2)
          (txt "2×" 1400 668 52 AMBER "center" 800)))))

  ;; 2 -- concurrent overwrites
  (define (s-wall2 t)
    (let* ((fx 610) (fy 170)
           (owner (lambda (i)
                    (cond ((and (memv i '(1 2)) (between? t 3.4 4.6)) AZURE)
                          ((and (= i 5) (between? t 4.6 5.8)) VIOLET)
                          ((and (= i 3) (>= t 5.8)) AMBER)
                          (else FAINT))))
           (flash (lambda (t0) (* (ramp t t0 (+ t0 0.1)) (- 1 (ramp t (+ t0 0.2) (+ t0 0.8)))))))
      (doc-card fx fy 380 330 "api.py" VIOLET)
      (do ((i 0 (+ i 1))) ((= i 8))
        (box (+ fx 28) (+ fy 62 (* i 32)) (* 320 (vector-ref LENS i)) 9 4.5 (owner i) #f))
      (fade (flash 3.4) (box fx fy 380 330 12 #f AZURE 5))
      (fade (flash 4.6) (box fx fy 380 330 12 #f VIOLET 5))
      (fade (flash 5.8) (box fx fy 380 330 12 #f AMBER 5))
      (avatar 250 230 32 AZURE 'agent "agent-a")
      (avatar 250 420 32 AMBER 'human "human")
      (avatar 1350 320 32 VIOLET 'agent "agent-b")
      (fade (ro t 0.6 1.2)
        (mtxt "edits L2–L3" 310 176 14 AZURE)
        (mtxt "edits L4" 310 366 14 AMBER)
        (mtxt "edits L6" 1300 262 14 VIOLET))
      (fade (* (ramp t 2.6 2.9) (- 1 (ramp t 3.4 3.8))) (arrow 300 240 600 260 AZURE 3 (ro t 2.7 3.4)))
      (fade (* (ramp t 3.8 4.1) (- 1 (ramp t 4.6 5.0))) (arrow 1300 330 1000 330 VIOLET 3 (ro t 3.9 4.6)))
      (fade (* (ramp t 5.0 5.3) (- 1 (ramp t 5.8 6.2))) (arrow 300 420 600 400 AMBER 3 (ro t 5.1 5.8)))
      (fade (ro t 4.7 5.1) (chip "✗ edit lost" 190 318 RED 15))
      (fade (ro t 5.9 6.3) (chip "✗ edit lost" 1270 400 RED 15))
      (fade (ro t 6.3 6.8) (txt "last write wins" 800 540 22 RED "center" 700))
      ;; the shared working directory
      (fade (ro t 7.2 7.9)
        (box 330 580 940 190 14 PANEL LINE)
        (mtxt "shared working dir  ./build" 356 610 16 DIM "left" 600)
        (mtxt "agent-a: make test" 360 660 16 AZURE)
        (mtxt "agent-b: make test" 360 730 16 VIOLET)
        (bar 560 650 180 18 (ro t 7.6 9.6) AZURE)
        (bar 560 720 180 18 (ro t 7.8 9.8) VIOLET)
        (chip "out.o" 860 660 AMBER 15)
        (chip "fixtures.db" 850 730 AMBER 15)
        (let ((f (pulse t 14)))
          (fade f (arrow 745 659 852 659 AZURE 2) (arrow 745 729 842 729 VIOLET 2))
          (fade (- 1 f) (arrow 745 659 842 723 VIOLET 2) (arrow 745 729 852 666 AZURE 2)))
        (fade (ro t 9.9 10.4)
          (mtxt "FAIL · fixtures mutated" 1010 660 16 RED "left" 600)
          (mtxt "FAIL · out.o clobbered" 1010 730 16 RED "left" 600)))))

  ;; 3 -- the token black hole
  (define (s-wall3 t)
    (let* ((g (ro t 0 4)) (h (+ 240 (* 360 g))) (x 180) (y 170))
      (doc-card x y 300 h "store.md" AMBER)
      (let ((n (int (/ (- h 60) 11))))
        (do ((i 0 (+ i 1))) ((>= i n))
          (box (+ x 22) (+ y 52 (* i 11)) (* 250 (vector-ref LENS (mod i 12))) 5 2.5 FAINT #f)))
      (let ((hy (+ y (* 0.62 h))))
        (fade (ro t 2 2.6)
          (box (+ x 16) (- hy 8) 268 22 5 AMBER #f)
          (line (+ x 290) (+ hy 3) 560 (+ hy 3) AMBER 2)
          (mtxt "validate_patch()" 570 (- hy 8) 16 AMBER "left" 600)
          (mtxt "310 tokens" 570 (+ hy 16) 15 AMBER)))
      (txt (string-append "+" (fmt (* 1240 g)) " lines") 520 200 24 GREEN "left" 700)
      (txt "−0 lines" 520 234 20 RED "left" 600)
      (avatar 860 330 38 AZURE 'agent "agent-a")
      (fade (ro t 0.8 1.4) (bubble 860 240 "need: validate_patch()" AZURE))
      ;; the whole file pours into context
      (let ((f (* 0.92 (ro t 4.2 8.2))))
        (fade (ro t 3.8 4.3)
          (txt "context window" 1010 420 19 DIM "left" 600)
          (bar 1010 444 440 50 f (cond ((< f 0.5) GREEN) ((< f 0.8) AMBER) (else RED)))
          (box 1012 446 5 46 2 AMBER #f)
          (mtxt (string-append (fmt (* 42000 f)) " / 42,000 tokens") 1010 526 17 INK))
        (when (between? t 4.2 8.4)
          (do ((i 0 (+ i 1))) ((= i 16))
            (let* ((ph (- (* t 0.9) (* i 0.0625))) (p (- ph (floor ph)))
                   (sy (+ y 60 (* (- h 80) (vector-ref LENS (mod (* 5 i) 12))))))
              (fade (* (sin (* 3.1416 p)) 0.8)
                (box (lerp 480 1010 p) (lerp sy 468 (ez p)) 26 5 2.5 AMBER #f)))))
        (fade (ro t 8.3 8.9)
          (txt "92% spent · 0.7% needed" 1010 590 26 RED "left" 700)
          (txt "the file is the unit of addressing" 1010 628 18 DIM)))))

  ;; 4 -- runaway long-tail topology
  (define notes
    (begin (set! seed 777)
           (let loop ((i 0) (acc '()))
             (if (= i 170) (list->vector (reverse acc))
                 (loop (+ i 1) (cons (list (+ 110 (* 620 (rnd))) (+ 185 (* 560 (rnd))) (rnd)) acc))))))
  (define (s-wall4 t)
    (let ((n (int (* 170 (ro t 0 3.5)))))
      (do ((i 0 (+ i 1))) ((>= i n))
        (let ((q (vector-ref notes i)))
          (box (car q) (cadr q) 11 14 2 (if (< (caddr q) 0.15) AZURE FAINT) #f))))
    (fade (ro t 2 2.6)
      (txt "thousands of isolated atomic notes" 425 790 20 DIM "center" 600))
    ;; three monoliths; the middle one gets split at t=6
    (let ((hs '#(470 560 400)) (xs '#(820 1010 1200)) (cut (ro t 6.3 8)))
      (do ((m 0 (+ m 1))) ((= m 3))
        (let* ((hh (* (vector-ref hs m) (ro t (+ 3 (* 0.3 m)) (+ 5.5 (* 0.3 m)))))
               (x (vector-ref xs m)) (y0 (- 760 hh)))
          (if (and (= m 1) (> cut 0))
              (do ((c 0 (+ c 1))) ((= c 4))
                (let* ((ch (/ hh 4)) (dx (* cut (if (even? c) -40 40)))
                       (dy (* cut (* (- c 1.5) 18))))
                  (at (+ x dx) (+ y0 (* c ch) dy) 1
                    (box 0 0 140 (- ch 2) 8 PANEL2 LINE 1.5)
                    (lines 16 14 110 (int (/ (- ch 20) 12)) 12 FAINT c)
                    (poly (list (cons 70 0) (cons (+ 70 (* 30 (sin c))) (* 0.5 ch)) (cons 70 ch)) AMBER 3))
                  (when (and (> c 0) (> cut 0.5))
                    (fade (ramp cut 0.5 1)
                      (cross (+ x 70) (+ y0 (* c ch) (* cut (* (- c 2) 18))) 9 RED)))))
              (begin
                (box x y0 140 hh 8 PANEL2 LINE 1.5)
                (lines (+ x 16) (+ y0 14) 110 (int (/ (- hh 20) 12)) 12 FAINT m)
                (when (= m 1)
                  (poly (list (cons (+ x 70) y0) (cons (+ x 90) (+ y0 (* 0.3 hh)))
                              (cons (+ x 50) (+ y0 (* 0.6 hh))) (cons (+ x 70) 760))
                        AMBER 3))))))
      (fade (ro t 5 5.6)
        (txt "a handful of massive files, months of edits" 1080 790 20 DIM "center" 600))
      (fade (* (ramp t 5.9 6.1) (- 1 (ramp t 6.9 7.2)))
        (dash! #t)
        (do ((c 1 (+ c 1))) ((= c 4))
          (line 970 (- 760 (* 560 (/ (- 4 c) 4))) (lerp 970 1200 (ro t 6 6.9)) (- 760 (* 560 (/ (- 4 c) 4))) RED 2))
        (dash! #f))
      (fade (ro t 7.6 8.2)
        (txt "logical flow:" 1370 330 24 RED "left" 700)
        (txt "shattered" 1370 364 24 RED "left" 700))))

  ;; 5 -- drifting indexes
  (define (s-wall5 t)
    (let* ((k (rz t 3.5 5))
           (slot (lambda (i)                ; B (1) moves after E (4)
                   (cond ((= i 1) (lerp 1 4 k))
                         ((and (<= 2 i) (<= i 4)) (- i k))
                         (else i))))
           (py (lambda (s) (+ 190 (* s 92))))
           (labels '#("¶A" "¶B" "¶C" "¶D" "¶E" "¶F"))
           (cols (vector AZURE AMBER VIOLET TEAL PINK GREEN))
           (moved (> t 5)))
      (for-each
       (lambda (i)
        (let ((y (py (slot i))))
          (box 700 y 420 80 10 PANEL2 (if (and (= i 1) (between? t 3.4 5.2)) AMBER LINE) 1.5)
          (txt (vector-ref labels i) 722 (+ y 26) 18 (vector-ref cols i) "left" 700)
          (lines 770 (+ y 20) 320 3 18 FAINT i)))
       '(0 2 3 4 5 1))
      ;; line-number gutter: fixed, the text slides past it
      (do ((s 0 (+ s 1))) ((= s 6))
        (mtxt (string-append "L" (number->string (+ 12 (* 18 s)))) 680 (+ (py s) 40) 13 FAINT "right"))
      (mtxt "index" 150 196 15 DIM "left" 600)
      (let ((rows '((1 "vec#0012" "¶B refund rule") (3 "vec#0013" "¶D retries")
                    (4 "fee()" "¶E fee table"))))
        (let loop ((r rows) (j 0))
          (unless (null? r)
            (let* ((s (car (car r))) (ry (+ 250 (* 90 j))) (ty (+ (py s) 40))
                   (c (if moved RED AZURE)))
              (box 150 (- ry 28) 360 56 8 PANEL c 1.5)
              (mtxt (cadr (car r)) 166 (- ry 6) 15 c "left" 600)
              (mtxt (string-append "→ L" (number->string (+ 12 (* 18 s))) "  "
                                   (caddr (car r)))
                    166 (+ ry 16) 14 (if moved RED DIM))
              (arrow 512 ry 694 ty c 2)
              (when moved (fade (ro t 5 5.5) (txt "?" 586 (- (lerp ry ty 0.5) 16) 26 RED "center" 800)))
              (loop (cdr r) (+ j 1))))))
      (fade (ro t 5.2 5.8) (chip "stale · no warning" 150 540 RED 15))
      (avatar 1350 290 34 AZURE 'agent "agent-a")
      (fade (ro t 6 6.6)
        (bubble 1350 200 "per ¶B: refunds are final" RED)
        (mtxt "(it read ¶C) → hallucination" 1350 400 15 RED "center" 600))
      (fade (ro t 8 8.6)
        (box 1180 470 330 150 12 PANEL2 LINE)
        (mtxt "billing.md" 1200 498 15 DIM)
        (txt "see design ¶B for refunds" 1200 540 17 INK)
        (dash! #t) (line 1180 540 1125 (+ (py 1) 40) RED 2) (dash! #f)
        (cross 1150 (lerp 540 (+ (py 1) 40) 0.5) 9 RED)
        (chip "$ git status → clean" 1180 660 GREEN 15)
        (txt "semantic break: invisible to Git" 1180 712 17 RED "left" 600))))

  ;; the 12-block graph shared by the shift and the outro
  (define gnodes
    (vector (list 520 330 AZURE "doc" "§Overview") (list 800 250 AZURE "doc" "§Write path")
            (list 1080 330 AZURE "doc" "§Recovery") (list 1180 500 VIOLET "code" "commit()")
            (list 1080 670 VIOLET "code" "store.py") (list 800 740 GREEN "test" "test W3")
            (list 520 670 VIOLET "macro" "define-block") (list 420 500 AMBER "adr" "ADR-12")
            (list 660 440 VIOLET "fn" "fee()") (list 940 440 AZURE "doc" "§Billing")
            (list 660 580 GREEN "test" "test W7") (list 940 580 AMBER "req" "R-118")))
  (define gedges '((0 1) (1 2) (1 3) (2 4) (3 5) (3 9) (4 6) (6 8) (7 0) (8 9) (8 10)
                   (9 11) (11 3) (10 5) (7 11) (2 3)))
  (define (gpos i) (let ((n (vector-ref gnodes i))) (cons (car n) (cadr n))))
  (define (draw-edges alpha-of)
    (for-each (lambda (e)
                (let ((a (gpos (car e))) (b (gpos (cadr e))) (al (alpha-of e)))
                  (fade al (line (car a) (cdr a) (car b) (cdr b) "#3a4a80" 2))))
              gedges))
  (define (draw-gnode i x y s)
    (let ((n (vector-ref gnodes i)))
      (at x y s
        (box -80 -26 160 52 10 PANEL2 (caddr n) 2)
        (mtxt (cadddr n) -68 -10 11 (caddr n) "left" 600)
        (mtxt (string-append "b:" (hex (+ 4096 (* 97 i)))) 70 -10 11 FAINT "right")
        (txt (list-ref n 4) -68 12 16 INK "left" 600))))

  ;; 6 -- the shift
  (define (s-shift t)
    (let ((m (rz t 1.4 3.6)))
      (fade (- 1 (ramp t 1.6 2.6))
        (doc-card 300 250 220 300 "design.md" AZURE)
        (doc-card 690 250 220 300 "store.py" VIOLET)
        (doc-card 1080 250 220 300 "tests.ss" GREEN))
      (draw-edges (lambda (e) (ro t (+ 3.4 (* 0.1 (car e))) (+ 4 (* 0.1 (car e))))))
      (do ((i 0 (+ i 1))) ((= i 12))
        (let* ((f (quotient i 4)) (r (mod i 4))
               (sx (+ 410 (* 390 f))) (sy (+ 330 (* 56 r)))
               (g (gpos i)))
          (draw-gnode i (lerp sx (car g) m) (lerp sy (cdr g) m) (lerp 0.9 1 m))))
      (fade (ro t 5.8 6.6)
        (dbox 1320 620 200 130 10 DIM)
        (mtxt "design.md" 1340 650 15 DIM)
        (lines 1340 676 160 4 16 FAINT)
        (txt "projection" 1420 776 17 DIM "center" 600)
        (dash! #t)
        (line 1180 526 1320 650 FAINT 1.5) (line 1080 356 1320 630 FAINT 1.5)
        (dash! #f))))

  ;; 7 -- a minimal query surface
  (define term-lines
    '((0.4 cmd "> (outline \"design/store\")")
      (1.6 out "(b:7f3a section \"Write path\"       412)")
      (1.8 out "(b:7f3b section \"Scratchpads\"      286)")
      (2.0 out "(b:91c0 code    \"commit.ss\"       1904)")
      (2.2 out "(b:91c4 def     \"stale-baseline?\"  138)")
      (3.6 cmd "> (search \"stale baseline\")")
      (4.6 out "(b:91c4 0.93 138)")
      (6.0 cmd "> (refs b:91c4)")
      (7.0 out "(b:7f3b mentions) (t:w3 checks)")
      (7.2 out "(adr:12 decides)")))
  (define (s-f1 t)
    (box 150 170 880 590 14 "#0b1128" LINE 1.5)
    (circle 176 196 6 RED #f) (circle 198 196 6 AMBER #f) (circle 220 196 6 GREEN #f)
    (mtxt "store  —  agent-a" 590 197 14 FAINT "center")
    (let loop ((ls term-lines) (y 250))
      (unless (null? ls)
        (let* ((l (car ls)) (t0 (car l)) (s (caddr l)))
          (when (>= t t0)
            (if (eq? (cadr l) 'cmd)
                (mtxt (typed s (ramp t t0 (+ t0 0.9))) 180 y 20 GREEN)
                (let* ((sp (let find ((i (- (string-length s) 2)))
                             (if (or (<= i 0) (char=? (string-ref s i) #\space)) i (find (- i 1)))))
                       (head (substring s 0 (+ sp 1)))
                       (tail (substring s (+ sp 1) (string-length s)))
                       (tok? (and (> (string-length tail) 1)
                                  (char-numeric? (string-ref tail 0)))))
                  (mtxt head 180 y 20 INK)
                  (mtxt tail (+ 180 (text-w head 20 400 #t)) y 20 (if tok? AMBER INK)))))
          (loop (cdr ls) (+ y 44)))))
    (fade (ro t 0 0.6)
      (txt "verbs" 1090 196 17 DIM "left" 600))
    (let ((vs '(("outline" 0.4) ("search" 3.6) ("refs" 6.0) ("batch" 99))))
      (let loop ((vs vs) (y 240))
        (unless (null? vs)
          (let ((on (>= t (cadr (car vs)))))
            (chip (car (car vs)) 1090 y (if on AZURE FAINT) 18 on))
          (loop (cdr vs) (+ y 50)))))
    (fade (ro t 4.8 5.4)
      (box 1090 450 380 130 12 PANEL AMBER 1.5)
      (txt "footprint, before reading" 1112 482 17 DIM "left" 600)
      (mtxt "b:91c4 · 138 tokens" 1112 522 22 AMBER "left" 700)
      (check 1122 556 7 GREEN) (txt "fits the budget" 1140 558 16 GREEN))
    (fade (ro t 8 8.6)
      (let loop ((ss '("no rendering markup" "one item per line" "no pretty-print mode"))
                 (y 630))
        (unless (null? ss)
          (check 1100 y 7 GREEN)
          (txt (car ss) 1120 (+ y 2) 18 INK)
          (loop (cdr ss) (+ y 40))))))

  ;; 8 -- one unified graph
  (define f2-nodes                        ; name (repo-x repo-y) (gx gy) colour tag id
    (vector (list "R-118 requirement" 1100 330 330 260 AMBER "requirement" "b:3f1a")
            (list "§Write path" 1100 440 330 470 AZURE "design section" "b:7f3a")
            (list "ADR-12" 1100 550 330 680 AMBER "decision record" "b:a012")
            (list "discussion #41" 1100 660 1270 560 TEAL "discussion" "b:d041")
            (list "commit.ss" 500 330 800 300 VIOLET "source file" "b:91c0")
            (list "define-block" 500 440 800 520 PINK "scheme macro" "b:91c2")
            (list "validate_patch()" 500 550 800 710 VIOLET "python function" "b:b7e9")
            (list "test W3" 500 660 1270 300 GREEN "test" "b:e0w3")))
  (define f2-edges                        ; from to label main?
    '((0 4 "met by" #t) (4 7 "checked by" #t) (7 3 "decided in" #t)
      (4 5 "uses" #f) (6 5 "uses" #f) (1 4 "specifies" #f) (2 1 "supersedes" #f)))
  ;; where the segment from (ax,ay) to a box centred on (bx,by) meets it
  (define (box-edge ax ay bx by hw hh)
    (let* ((dx (- bx ax)) (dy (- by ay))
           (k (min (if (= dx 0) 99 (/ hw (abs dx))) (if (= dy 0) 99 (/ hh (abs dy))))))
      (cons (- bx (* dx k)) (- by (* dy k)))))
  (define (f2-pos i m)
    (let ((n (vector-ref f2-nodes i)))
      (cons (lerp (list-ref n 1) (list-ref n 3) m) (lerp (list-ref n 2) (list-ref n 4) m))))
  (define (s-f2 t)
    (let ((m (rz t 2.6 4.4)) (wall (- 1 (ramp t 2 3))))
      (fade wall
        (dbox 330 270 340 460 16 DIM) (dbox 930 270 340 460 16 DIM)
        (mtxt "repo/" 350 300 16 DIM "left" 600) (mtxt "docs/" 950 300 16 DIM "left" 600)
        (rect 796 240 8 520 RED)
        (txt "filesystem boundary" 800 225 16 RED "center" 600))
      (let loop ((es f2-edges) (j 0))
        (unless (null? es)
          (let* ((e (car es)) (a (f2-pos (car e) m)) (b (f2-pos (cadr e) m))
                 (p (ro t (+ 4.6 (* 0.5 j)) (+ 5.3 (* 0.5 j))))
                 (main (cadddr e))
                 (c (if main AZURE "#3a4a80")))
            (let ((s0 (box-edge (car b) (cdr b) (car a) (cdr a) 131 37))
                  (s1 (box-edge (car a) (cdr a) (car b) (cdr b) 131 37)))
              (arrow (car s0) (cdr s0) (car s1) (cdr s1) c (if main 3 2) p))
            (fade (ramp p 0.8 1)
              (mtxt (caddr e) (lerp (car a) (car b) 0.5) (- (lerp (cdr a) (cdr b) 0.5) 12)
                    13 (if main AZURE DIM) "center" 600))
            (loop (cdr es) (+ j 1)))))
      ;; a token travelling the main chain
      (when (> t 8.4)
        (let* ((ph (* 0.45 (- t 8.4))) (seg (mod (int ph) 3)) (p (- ph (floor ph)))
               (pairs '#((0 . 4) (4 . 7) (7 . 3)))
               (a (f2-pos (car (vector-ref pairs seg)) 1)) (b (f2-pos (cdr (vector-ref pairs seg)) 1)))
          (circle (lerp (car a) (car b) (ez p)) (lerp (cdr a) (cdr b) (ez p)) 8 AZURE #f)))
      (do ((i 0 (+ i 1))) ((= i 8))
        (let ((n (vector-ref f2-nodes i)) (p (f2-pos i m)))
          (node (car p) (cdr p) 250 62 (list-ref n 5) (list-ref n 6) (car n) (list-ref n 7))))))

  ;; 9 -- global backlinks
  (define (s-f3 t)
    (mtxt (typed "> (refs b:91c4)" (ramp t 0.3 1.2)) 130 190 20 GREEN)
    (let ((cx 430) (cy 470)
          (bl `(("design §Billing" ,AZURE) ("prose ¶ pricing" ,AZURE) ("lesson L-7" ,PINK)
                ("test W3" ,GREEN) ("ADR-12" ,AMBER))))
      (let loop ((bl bl) (j 0))
        (unless (null? bl)
          (let* ((a (- (* j 1.2566) 1.5708)) (x (+ cx (* 250 (cos a)))) (y (+ cy (* 200 (sin a))))
                 (p (ro t (+ 1.3 (* 0.35 j)) (+ 2 (* 0.35 j)))))
            (fade (ramp p 0 0.3)
              (arrow x y (lerp x cx 0.62) (lerp y cy 0.62) (cadr (car bl)) 2.5 p)
              (box (- x 90) (- y 22) 180 44 10 PANEL2 (cadr (car bl)) 2)
              (txt (car (car bl)) x (+ y 1) 16 INK "center" 600))
            (loop (cdr bl) (+ j 1)))))
      (circle cx cy (+ 52 (* 6 (pulse t 4) (ramp t 1 2))) #f AMBER 2)
      (circle cx cy 46 PANEL2 AMBER 3)
      (mtxt "fee()" cx (- cy 6) 20 AMBER "center" 700)
      (mtxt "b:91c4" cx (+ cy 18) 12 FAINT "center"))
    (fade (ro t 3.4 4)
      (mtxt "> (log b:91c4)" 130 722 17 GREEN)
      (do ((i 0 (+ i 1))) ((= i 6))
        (circle (+ 330 (* 36 i)) 722 7 (if (= i 5) AMBER VIOLET) #f))
      (mtxt "6 revisions" 560 722 15 DIM))
    ;; the measurements
    (fade (ro t 5 5.6)
      (box 800 170 680 590 14 PANEL LINE)
      (txt "tokens to answer a question" 830 210 22 INK "left" 700)
      (txt "vs. reading the full document each time" 830 240 16 DIM)
      (let loop ((rows '(("read the full document" 100 FAINT) ("outline, then read" 20 AZURE)
                         ("search + read the block" 15 GREEN)))
                 (y 320) (j 0))
        (unless (null? rows)
          (let* ((r (car rows)) (v (cadr r))
                 (c (case (caddr r) ((FAINT) FAINT) ((AZURE) AZURE) (else GREEN)))
                 (p (ro t (+ 5.6 (* 0.6 j)) (+ 6.8 (* 0.6 j)))))
            (txt (car r) 830 y 18 INK "left" 500)
            (box 830 (+ y 18) (* 5.4 v p) 34 6 c #f)
            (txt (string-append (number->string (int (* v p))) "%")
                 (+ 842 (* 5.4 v p)) (+ y 36) 20 c "left" 700)
            (loop (cdr rows) (+ y 104) (+ j 1)))))
      (fade (ro t 8.6 9.2)
        (line 830 628 1450 628 LINE 1)
        (txt "corpus outline vs. raw Markdown" 830 662 18 INK)
        (box 830 678 (* 5.4 6 (ro t 8.8 9.8)) 30 6 AMBER #f)
        (txt "6%" (+ 842 (* 5.4 6 (ro t 8.8 9.8))) 694 20 AMBER "left" 700))
      (fade (ro t 9.4 10)
        (mtxt "56 questions · 20 real engineering documents" 830 738 14 DIM))))

  ;; 10 -- deterministic context assembly
  (define (s-f4 t)
    (fade (ro t 0 0.6)
      (box 110 170 400 300 14 PANEL2 AZURE 2)
      (mtxt "task  b:t204" 134 202 15 AZURE "left" 600)
      (txt "Add a refund path" 134 238 24 INK "left" 700)
      (let loop ((rs '(("premises" "P-3, P-7") ("goals" "refund < 14 days")
                       ("deliverables" "refund.ss, test W9")))
                 (y 290))
        (unless (null? rs)
          (mtxt (car (car rs)) 134 y 15 DIM)
          (txt (cadr (car rs)) 280 y 17 INK)
          (loop (cdr rs) (+ y 42))))
      (txt "budget" 134 430 16 DIM)
      (mtxt "8,000 tokens" 220 430 18 AMBER "left" 700))
    (fade (ro t 1.6 2.2)
      (box 560 170 490 330 14 "#0b1128" LINE)
      (mtxt "query  ·  Datalog over in-memory facts" 584 202 14 DIM "left" 600)
      (let loop ((ls '("live(B) :- block(B),"
                       "   not superseded(B), not refuted(B)."
                       "closure(T,B) :- premise(T,P),"
                       "   depends*(P,B)."
                       "authority(S,B) :- defines(B,S),"
                       "   live(B), in_scope(B)."))
                 (y 246) (j 0))
        (unless (null? ls)
          (mtxt (typed (car ls) (ramp t (+ 2 (* 0.4 j)) (+ 2.5 (* 0.4 j)))) 584 y 16
                (if (even? j) TEAL INK))
          (loop (cdr ls) (+ y 32) (+ j 1))))
      (fade (ro t 4.4 5)
        (let* ((w1 (chip "in memory" 584 466 GREEN 13))
               (w2 (chip "no disk writes" (+ 594 w1) 466 GREEN 13)))
          (chip "no user code" (+ 604 w1 w2) 466 GREEN 13))))
    (fade (ro t 0.8 1.4)
      (let loop ((fs '("block" "field" "tree" "defines" "verified" "premise"
                       "depends" "uses" "implements" "supersedes" "refutes"))
                 (x 110) (y 540))
        (unless (null? fs)
          (let* ((w (+ 10 (text-w (car fs) 14 500 #t) 20)))
            (if (> (+ x w) 1050)
                (loop fs 110 (+ y 42))
                (begin (chip (car fs) x y FAINT 14)
                       (loop (cdr fs) (+ x w) y))))))
      (mtxt "facts" 110 505 14 DIM "left" 600))
    ;; the compiled working set
    (let ((tiers `(("CONSTRAINTS · must-read" ,RED 4 5.2) ("evidence" ,AZURE 3 6.6)
                   ("counterexamples" ,PINK 1 7.6) ("background" ,VIOLET 2 8.2)
                   ("stale verifications" ,AMBER 1 8.8)))
          (used 0))
      (fade (ro t 4.8 5.4)
        (txt "context  →  working set" 1100 186 18 DIM "left" 600)
        (let loop ((ts tiers) (y 222))
          (unless (null? ts)
            (let* ((tr (car ts)) (c (cadr tr)))
              (mtxt (car tr) 1100 y 14 c "left" 700)
              (do ((i 0 (+ i 1))) ((= i (caddr tr)))
                (let* ((t0 (+ (cadddr tr) (* 0.25 i))) (p (ro t t0 (+ t0 0.5))))
                  (when (> p 0)
                    (set! used (+ used (* p (if (= i 0) 900 560))))
                    (let ((x (lerp 800 (+ 1100 (* 92 i)) p)) (yy (lerp 600 (+ y 16) p)))
                      (box x yy 84 26 6 PANEL2 c 1.5)
                      (mtxt (string-append "b:" (hex (+ 160 (* 37 i) (* 11 (string-length (car tr))))))
                            (+ x 42) (+ yy 14) 12 c "center")))))
              (loop (cdr ts) (+ y 70)))))
        ;; ADR-7 is superseded: barred from the must-read tier
        (let ((p (ro t 6 6.8)) (b (ro t 6.8 7.6)))
          (when (and (> p 0) (< b 1))
            (fade (- 1 b)
              (let ((x (lerp 800 1400 p)) (y (lerp 600 (+ 236 (* 50 b)) p)))
                (box x y 90 26 6 PANEL2 FAINT 1.5)
                (mtxt "ADR-7" (+ x 45) (+ y 14) 12 FAINT "center")
                (when (> p 0.95) (cross (+ x 100) (+ y 13) 7 RED))))))
        (txt "budget" 1100 580 15 DIM)
        (bar 1170 568 290 22 (/ used 8000) (if (> used 7600) AMBER GREEN))
        (mtxt (string-append (fmt used) " / 8,000") 1460 604 13 DIM "right"))
      (fade (ro t 9.4 10)
        (mtxt "EXCLUDED" 1100 640 14 FAINT "left" 700)
        (let loop ((xs '(("b:44d" "over budget by 1,120 t") ("ADR-7" "superseded by ADR-12")
                         ("b:c10" "speculative")))
                   (y 670) (j 0))
          (unless (null? xs)
            (fade (ro t (+ 9.6 (* 0.5 j)) (+ 10.1 (* 0.5 j)))
              (mtxt (car (car xs)) 1100 y 15 DIM "left" 600)
              (txt (cadr (car xs)) 1180 y 16 RED))
            (loop (cdr xs) (+ y 32) (+ j 1)))))))

  ;; 11 -- the IDE
  (define code-lines
    '((12 kw "from" nm " store " kw "import" nm " blocks, log")
      (13)
      (15 kw "def " fn "$" nm "(writer, drafts, base):")
      (16 nm "    cur = log.version()")
      (17 kw "    if" nm " base != cur:")
      (18 kw "        raise" nm " StaleBaseline(base, cur, log.since(base))")
      (19 kw "    return" nm " blocks.install(writer, drafts)")
      (20)
      (21 kw "def " fn "refund" nm "(order):")
      (22 nm "    ...  " fn "$" nm "(order.writer, [draft], base)")))
  (define (s-f5 t)
    (let* ((rn (ro t 5 5.8))
           (fname (if (> rn 0.5) "apply_patch" "commit_patch")))
      (box 100 170 930 590 14 "#0b1128" LINE)
      (box 100 170 930 44 14 "#141d3c" #f)
      (box 116 180 170 34 8 "#0b1128" #f)
      (mtxt "commit.py" 136 198 15 INK) (mtxt "design.md" 316 198 15 FAINT)
      (fade (ro t 10.6 11.2) (chip "scratchpad · agent-b draft" 760 194 AMBER 13))
      (let loop ((ls code-lines) (y 262))
        (unless (null? ls)
          (let ((l (car ls)))
            (when (= (car l) 15)
              ;; the semantic lens above the definition
              (mtxt "3 design sections · 2 lessons · changed by agent-b under R-118 · test W3"
                    176 y 14 (if (between? t 1.8 4.8) AZURE FAINT))
              (set! y (+ y 32)))
            (mtxt (number->string (car l)) 150 y 16 FAINT "right")
            (let seg ((ps (cdr l)) (x 176))
              (unless (null? ps)
                (let* ((kind (car ps))
                       (s0 (cadr ps)) (s (if (string=? s0 "$") fname s0))
                       (c (case kind ((kw) VIOLET) ((fn) AZURE) (else INK)))
                       (w (text-w s 18 400 #t)))
                  (when (and (string=? s0 "$") (between? rn 0.05 0.99))
                    (box (- x 4) (- y 14) (+ w 8) 28 4 "#2a3a70" #f))
                  (mtxt s x y 18 c)
                  (seg (cddr ps) (+ x w)))))
            (loop (cdr ls) (+ y 38)))))
      ;; hover card
      (fade (* (ro t 2.2 2.8) (- 1 (ramp t 4.6 5)))
        (box 180 392 620 104 10 PANEL AZURE 2)
        (txt "Design §Write path" 200 422 17 AZURE "left" 700)
        (txt "Commits are atomic and serialized by the store;" 200 450 16 INK)
        (txt "a stale baseline is refused, never merged silently." 200 476 16 INK))
      (fade (* (ro t 5.8 6.3) (- 1 (ramp t 8.8 9.2)))
        (toast "rename · 1 atomic change · IDs unchanged" 565 730 GREEN))
      ;; right panel: first the stale docs, then the precise test run
      (box 1070 170 420 590 14 PANEL LINE)
      (fade (* (ro t 0.6 1.2) (- 1 (ramp t 5.2 5.6)))
        (txt "language server" 1094 210 16 DIM "left" 600)
        (let loop ((xs '("native, on real files" "IntelliSense intact" "diagnostics live"))
                   (y 250))
          (unless (null? xs)
            (check 1102 y 7 GREEN) (txt (car xs) 1122 (+ y 1) 16 INK)
            (loop (cdr xs) (+ y 36))))
        (fade (ro t 3.2 3.8)
          (txt "on save → blocks" 1094 400 16 DIM "left" 600)
          (mtxt "commit.py" 1094 444 15 INK)
          (arrow 1190 444 1250 444 AZURE 2)
          (chip "b:91c0" 1262 444 VIOLET 14)
          (chip "b:91c4" 1262 488 VIOLET 14)
          (arrow 1190 450 1250 484 AZURE 2)))
      (fade (* (ro t 5.8 6.4) (- 1 (ramp t 9.2 9.6)))
        (mtxt (typed "> (refs \"commit_patch\")" (ramp t 6.2 7)) 1094 210 16 GREEN)
        (fade (ro t 7.2 7.6)
          (txt "prose that hasn't caught up" 1094 256 16 DIM "left" 600)
          (let loop ((xs '("¶ design §Write path, line 3" "¶ lesson L-7")) (y 296))
            (unless (null? xs)
              (box 1094 (- y 20) 372 40 8 PANEL2 RED 1.5)
              (txt (car xs) 1110 (+ y 1) 16 INK)
              (mtxt "stale" 1454 (+ y 1) 13 RED "right" 700)
              (loop (cdr xs) (+ y 52)))))
        (fade (ro t 8 8.4)
          (txt "edges that survived" 1094 420 16 DIM "left" 600)
          (let loop ((xs '("3 design sections" "2 lessons" "test W3")) (y 456))
            (unless (null? xs)
              (check 1102 y 7 GREEN) (txt (car xs) 1122 (+ y 1) 16 INK)
              (loop (cdr xs) (+ y 36))))))
      (fade (ro t 9.4 10)
        (txt "tests to rerun: one graph walk" 1094 210 16 DIM "left" 600)
        (let* ((ch (cons 1280 290))
               (cl (vector (cons 1160 420) (cons 1400 420)))
               (ts (vector (cons 1280 560) (cons 1140 560) (cons 1420 560)))
               (run (ro t 11.4 12.6)))
          (arrow 1280 312 1170 396 DIM 2) (arrow 1280 312 1390 396 DIM 2)
          (arrow 1280 312 1280 532 GREEN 2) (arrow 1160 442 1146 532 GREEN 2)
          (arrow 1400 442 1414 532 GREEN 2)
          (box 1200 268 160 44 10 PANEL2 AMBER 2)
          (mtxt "apply_patch" 1280 291 15 AMBER "center" 700)
          (box 1100 398 120 44 10 PANEL2 AZURE 2) (mtxt "refund" 1160 421 15 AZURE "center")
          (box 1340 398 120 44 10 PANEL2 AZURE 2) (mtxt "retry" 1400 421 15 AZURE "center")
          (let loop ((ns '("W3" "W7" "W9")) (i 0))
            (unless (null? ns)
              (let ((p (vector-ref ts i)))
                (circle (car p) (cdr p) 26 PANEL2 GREEN 2)
                (if (> run (* 0.3 (+ i 1)))
                    (check (car p) (cdr p) 8 GREEN)
                    (mtxt (car ns) (car p) (+ (cdr p) 1) 14 GREEN "center" 700)))
              (loop (cdr ns) (+ i 1))))
          (do ((i 0 (+ i 1))) ((= i 24))
            (circle (+ 1104 (* 15 i)) 640 4 FAINT #f))
          (mtxt "208 others: skipped" 1094 676 15 FAINT)
          (fade (ro t 12.4 13)
            (txt "3 of 212 tests rerun" 1094 722 22 GREEN "left" 700))))))

  ;; 12 -- zero-conflict workspaces
  (define (s-f6 t)
    (let* ((ver (cond ((> t 13.3) "v43") ((> t 6.2) "v42") (else "v41")))
           (flash (lambda (t0 c)
                    (fade (* (ramp t t0 (+ t0 0.1)) (- 1 (ramp t (+ t0 0.3) (+ t0 1))))
                      (box 610 170 380 120 14 #f c 6)))))
      (box 610 170 380 120 14 PANEL2 AZURE 2)
      (txt "main tree" 636 208 18 DIM "left" 600)
      (txt ver 636 256 40 INK "left" 800)
      (mtxt "serialized commits" 964 256 13 FAINT "right")
      (flash 6.2 GREEN) (flash 8.0 RED) (flash 13.3 GREEN)
      (let ((pads `((150 "agent-a" ,AZURE agent) (620 "agent-b" ,VIOLET agent)
                    (1090 "human" ,AMBER human))))
        (let loop ((ps pads) (j 0))
          (unless (null? ps)
            (let* ((p (car ps)) (x (car p)) (c (caddr p)) (a (ro t (* 0.3 j) (+ 0.6 (* 0.3 j)))))
              (fade a
                (dash! #t) (line 800 290 (+ x 180) 430 FAINT 1.5) (dash! #f)
                (box x 430 360 250 14 PANEL c 2)
                (avatar (+ x 40) 470 16 c (cadddr p) #f)
                (mtxt (cadr p) (+ x 72) 470 16 c "left" 700)
                (mtxt "scratchpad" (+ x 336) 470 13 FAINT "right")
                (let ((draft (cond ((and (= j 1) (> t 9.4)) "b:91c4″ merged")
                                   (else "b:91c4′ draft"))))
                  (chip draft (+ x 24) 530 c 15))
                (chip (string-append "env · sandbox-" (vector-ref '#("a" "b" "h") j))
                      (+ x 24) 576 TEAL 14)
                (let* ((prog (case j
                               ((0) (ro t 1 4.5))
                               ((1) (if (> t 10.4) (ro t 10.4 12.2) (ro t 1.2 4.8)))
                               (else (let ((ph (* 0.18 t))) (- ph (floor ph))))))
                       (done (and (>= prog 1) (< j 2))))
                  (mtxt "tests" (+ x 24) 634 14 DIM)
                  (bar (+ x 80) 624 200 18 prog (if done GREEN c))
                  (when done (check (+ x 306) 633 8 GREEN))))
              (loop (cdr ps) (+ j 1))))))
      ;; agent-a commits first
      (let ((p (ro t 5.2 6.2)))
        (when (between? t 5.2 6.3)
          (box (lerp 300 700 p) (lerp 520 250 p) 90 30 8 GREEN #f)
          (mtxt "commit" (+ (lerp 300 700 p) 45) (+ (lerp 520 250 p) 16) 13 BG "center" 700)))
      (fade (ro t 6.2 6.6) (chip "✓ agent-a committed" 150 390 GREEN 14))
      ;; agent-b is refused, merges, recommits
      (let* ((up (ro t 7 8)) (down (ro t 8 8.7))
             (y (if (< t 8) (lerp 520 280 up) (lerp 280 520 down))))
        (when (between? t 7 8.7)
          (box 755 y 90 30 8 (if (< t 8) VIOLET RED) #f)
          (mtxt "commit" 800 (+ y 16) 13 BG "center" 700)))
      (fade (* (ro t 8 8.5) (- 1 (ramp t 12.2 12.6)))
        (box 1030 160 430 160 12 PANEL RED 2)
        (mtxt "✗ stale-baseline" 1054 192 18 RED "left" 700)
        (mtxt "based on    v41" 1054 226 15 INK)
        (mtxt "current     v42" 1054 254 15 INK)
        (mtxt "since       1 record · agent-a" 1054 282 15 INK)
        (mtxt "(winner's content included)" 1054 306 13 DIM))
      (fade (ro t 9 9.4)
        (mtxt (if (> t 12.4) "" "merging in scratchpad…") 800 404 14 VIOLET "center" 600))
      (let ((p (ro t 12.4 13.3)))
        (when (between? t 12.4 13.4)
          (box 755 (lerp 520 250 p) 90 30 8 GREEN #f)
          (mtxt "commit" 800 (+ (lerp 520 250 p) 16) 13 BG "center" 700)))
      (fade (ro t 13.3 13.7) (chip "✓ agent-b committed" 1030 230 GREEN 14))
      (fade (ro t 2 2.6) (mtxt "still exploring · nothing touches main" 1270 720 14 AMBER "center"))))

  ;; 13 -- the Lisp machine
  (define (s-f7 t)
    (let* ((hist (ro t 8 9.4))
           (old (> hist 0.5))
           (cut (lerp 60 17 hist)))
      (box 110 170 580 270 14 PANEL2 VIOLET 2)
      (mtxt (if old "b:5e02 · scheme · @ v17" "b:5e02 · scheme") 134 202 15 VIOLET "left" 600)
      (fade (if old (ramp hist 0.5 1) (- 1 (* 2 hist)))
        (mtxt "(define (late-fee days)" 134 256 20 INK)
        (mtxt (if old "  (* 5 (max 0 (- days 7))))" "  (* 2 (max 0 (- days 14))))") 134 290 20
              (if old AMBER INK))
        (mtxt "(display (late-fee 30))" 134 336 20 INK))
      (let ((press (or (between? t 1.4 1.8) (between? t 10 10.4))))
        (box 134 376 110 40 10 (if press GREEN PANEL) GREEN 2)
        (mtxt "▶ eval" 189 397 16 (if press BG GREEN) "center" 700))
      (arrow 700 305 790 305 GREEN 3 (max (ro t 1.6 2.2) (ro t 10.2 10.8)))
      ;; the sandbox
      (box 800 170 680 270 14 PANEL TEAL 2)
      (mtxt "child process · isolated sandbox" 824 202 15 TEAL "left" 600)
      (let ((u (if (> t 10) (ro t 10.4 11.4) (ro t 2 3.6))))
        (let loop ((qs '(("wall-clock" "2.0 s" 0.21) ("memory" "64 MB" 0.34) ("output" "64 KB" 0.05)))
                   (y 248))
          (unless (null? qs)
            (let ((q (car qs)))
              (txt (car q) 824 y 16 DIM)
              (bar 960 (- y 9) 220 18 (* u (caddr q)) TEAL)
              (mtxt (cadr q) 1196 y 15 INK))
            (loop (cdr qs) (+ y 36)))))
      (let ((w1 (chip "(rnrs)" 1300 248 FAINT 13)))
        (chip "(store billing)" 1300 290 FAINT 13) w1)
      (fade (if (> t 10) (ro t 11.4 11.8) (* (ro t 3.6 4) (- 1 (ramp t 9.6 10))))
        (line 824 368 1456 368 LINE 1)
        (mtxt "stdout" 824 400 15 DIM)
        (mtxt (if (> t 10) "\"115\"" "\"32\"") 920 400 20 (if (> t 10) AMBER GREEN) "left" 700))
      ;; the log timeline
      (fade (ro t 5.6 6.2)
        (box 110 500 1370 240 14 PANEL LINE)
        (txt "the log" 134 536 18 DIM "left" 600)
        (txt "state = deterministic reduction of the log" 1456 536 16 FAINT "right")
        (line 170 620 1420 620 LINE 2)
        (do ((v 1 (+ v 1))) ((> v 60))
          (let ((x (lerp 170 1420 (/ (- v 1) 59))))
            (line x (if (= 0 (mod v 10)) 604 612) x 628 (if (<= v (int cut)) DIM FAINT) 2)))
        (let ((cx (lerp 170 1420 (/ (- cut 1) 59))))
          (circle cx 620 11 AMBER #f)
          (mtxt (string-append "v" (number->string (int (+ cut 0.5)))) cx 590 16 AMBER "center" 700))
        (fade (ro t 11.8 12.4)
          (chip "cut: log#1832 · v17 · reproducible" 170 690 GREEN 16 #t)))))

  ;; 14 -- outro
  (define (s-outro t)
    (fade (* 0.3 (ro t 0 1.5))
      (draw-edges (lambda (e) 1.0))
      (do ((i 0 (+ i 1))) ((= i 12))
        (let ((g (gpos i)))
          (draw-gnode i (+ (car g) (* 6 (sin (+ t i)))) (+ (cdr g) (* 6 (cos (+ (* 0.8 t) i)))) 1))))
    (box 170 300 1260 400 24 "rgba(10,15,31,0.9)" LINE 1)
    (fade (ro t 0.4 1.4)
      (txt "Blocks, not files." 800 390 68 INK "center" 800))
    (fade (ro t 1.4 2.4)
      (txt "One living graph for docs, code, tests and decisions —" 800 458 24 DIM "center")
      (txt "shared by humans and agents." 800 492 24 DIM "center"))
    (let* ((fs `(("query surface" ,AZURE) ("unified graph" ,VIOLET) ("backlinks" ,TEAL)
                 ("context compiler" ,RED) ("IDE lens" ,AMBER) ("scratchpads" ,GREEN)
                 ("Lisp machine" ,PINK)))
           (wsum (fold-left (lambda (acc f) (+ acc (text-w (car f) 16 500 #t) 22.4 14)) -14 fs)))
      (let loop ((fs fs) (x (- 800 (/ wsum 2))) (j 0))
        (unless (null? fs)
          (fade (ro t (+ 2.6 (* 0.2 j)) (+ 3 (* 0.2 j)))
            (chip (car (car fs)) x 600 (cadr (car fs)) 16))
          (loop (cdr fs) (+ x (text-w (car (car fs)) 16 500 #t) 22.4 14) (+ j 1)))))
    (fade (ro t 4.4 5.2)
      (mtxt "this film is Scheme, compiled to WebAssembly by Goeteia" 800 860 15 FAINT "center")))

  ;; ---------------------------------------------------------------
  ;; the reel: (duration draw captions)
  (define reel
    (vector
     (list 8.5 s-intro '())
     (list 12 s-wall1
           '((0 4 "An agent patches a design doc. Plain text accepts anything — no structural validation on write.")
             (4 7.2 "A whole section vanishes. The write reports success. Nothing throws.")
             (7.2 12 "Re-read the file after every write to verify it? That doubles the token burn.")))
     (list 12 s-wall2
           '((0 3.4 "Humans and agents reason in parallel — over the very same files.")
             (3.4 7 "No block-level isolation: the last write wins, and earlier work silently disappears.")
             (7 12 "Share a working directory to build or test, and they corrupt each other's execution state.")))
     (list 11 s-wall3
           '((0 4 "Docs and source grow monotonically: N lines added, zero deleted.")
             (4 8.2 "The file is the unit of addressing — needing one function means reading the whole monolith.")
             (8.2 11 "The context window fills with everything except what matters.")))
     (list 10 s-wall4
           '((0 3 "Over time a file-based knowledge base decays into two extremes:")
             (3 6.2 "thousands of isolated atomic notes, and a handful of massive files accumulated over months.")
             (6.2 10 "Splitting the monoliths by hand only shatters the logical flow.")))
     (list 11.5 s-wall5
           '((0 3.5 "External vector indexes and line-number maps are detached from the text itself.")
             (3.5 7.8 "Move a paragraph and the index goes stale — without warning. The agent is fed the wrong context.")
             (7.8 11.5 "Cross-file semantic breaks stay invisible to Git.")))
     (list 9 s-shift
           '((0 3 "So the system stops organizing content by files.")
             (3 6 "Blocks store documentation and source code alike — each one independently addressable.")
             (6 9 "Files are still projected when needed, but a file boundary no longer decides what is read, written or run.")))
     (list 11 s-f1
           '((0 3.6 "A compact query surface built for machine economics — no rendering markup at all.")
             (3.6 7.6 "outline, search, refs and batch answer in dense S-expressions, one item per line.")
             (7.6 11 "An agent sees the token footprint of what it's about to read — before reading it.")))
     (list 12.5 s-f2
           '((0 3 "The wall between the code repository and the document store is a filesystem accident.")
             (3 7.5 "A requirement, a design section, a source file, a Scheme macro, a Python function, an ADR: all equal blocks, each with a stable ID.")
             (7.5 12.5 "Edges are typed and directed: requirement → the code that meets it → the test that checks it → the discussion that decided it.")))
     (list 12.5 s-f3
           '((0 4.8 "One refs query answers the whole picture: which design, which prose, which test mentions this function. log gives its exact history.")
             (4.8 8.6 "search pinpoints the answering block, so the agent reads only that block — not the file around it.")
             (8.6 12.5 "Measured: 15% of the tokens of reading the full document. A corpus outline is just 6% of its raw Markdown.")))
     (list 14 s-f4
           '((0 4.4 "Agents gather context by intuition — and a missed premise only surfaces after the work is done.")
             (4.4 8.8 "query: Datalog-style rules over in-memory facts. Superseded and refuted blocks are barred from the must-read tier.")
             (8.8 14 "context: given a task and a token budget, compile the working set — and list every exclusion with its reason.")))
     (list 14 s-f5
           '((0 4.8 "People edit real projected files: the language server just works, and a lens shows what only the graph knows.")
             (4.8 9.2 "A rename is one atomic change. IDs never move, so edges survive — and one query names the prose left behind.")
             (9.2 14 "Agent drafts are reviewed with the whole IDE, and call edges rerun only the tests that guard the change.")))
     (list 15 s-f6
           '((0 4.8 "Every writer gets a private scratchpad — and its own isolated environment to compile and test in.")
             (4.8 9 "commit is atomic. A moved baseline is refused as stale-baseline — never silently overwritten.")
             (9 15 "The loser already holds the winner's records: it merges in its scratchpad, reruns its tests, and commits again.")))
     (list 14 s-f7
           '((0 4.8 "The store is also a runtime: Scheme blocks evaluate in place, like a modern Lisp machine.")
             (4.8 7.8 "Each evaluation runs in an isolated child process with wall-clock, memory and output quotas.")
             (7.8 14 "State is a deterministic reduction of the log — so old behavior runs at any historical cut, reproducibly.")))
     (list 9 s-outro '())))

  (define nscenes (vector-length reel))
  (define starts
    (let ((v (make-vector (+ nscenes 1) 0)))
      (do ((i 0 (+ i 1))) ((= i nscenes) v)
        (vector-set! v (+ i 1) (+ (vector-ref v i) (car (vector-ref reel i)))))))
  (define total (vector-ref starts nscenes))
  (define (scene-at g)
    (let loop ((i 0))
      (if (or (= i (- nscenes 1)) (< g (vector-ref starts (+ i 1)))) i (loop (+ i 1)))))

  ;; chapter buttons carry the names
  (define buttons (js-method (document) "querySelectorAll" ".ch"))
  (define (btn i) (js-index buttons i))
  (define (btn-attr i a)
    (if (< i (js->number (js-get buttons "length")))
        (js->string (js-method (btn i) "getAttribute" a))
        ""))
  (define kickers (let ((v (make-vector nscenes "")))
                    (do ((i 0 (+ i 1))) ((= i nscenes) v)
                      (vector-set! v i (btn-attr i "data-k")))))
  (define titles (let ((v (make-vector nscenes "")))
                   (do ((i 0 (+ i 1))) ((= i nscenes) v)
                     (vector-set! v i (btn-attr i "data-t")))))

  ;; captions: wrapped once per string
  (define cap-cache-s "") (define cap-cache-l '())
  (define (wrap s px maxw)
    (if (string=? s cap-cache-s)
        cap-cache-l
        (let loop ((cs (string->list s)) (word '()) (ln "") (acc '()))
          (define (flush-word)
            (let* ((w (list->string (reverse word)))
                   (cand (if (string=? ln "") w (string-append ln " " w))))
              (if (and (> (text-w cand px 500 #f) maxw) (not (string=? ln "")))
                  (values w (cons ln acc))
                  (values cand acc))))
          (cond
           ((null? cs)
            (let-values (((ln2 acc2) (flush-word)))
              (set! cap-cache-s s)
              (set! cap-cache-l (reverse (cons ln2 acc2)))
              cap-cache-l))
           ((char=? (car cs) #\space)
            (let-values (((ln2 acc2) (flush-word)))
              (loop (cdr cs) '() ln2 acc2)))
           (else (loop (cdr cs) (cons (car cs) word) ln acc))))))

  (define (draw-caption caps t)
    (for-each
     (lambda (c)
       (when (between? t (car c) (cadr c))
         (let* ((a (min (ramp t (car c) (+ (car c) 0.35)) (- 1 (ramp t (- (cadr c) 0.3) (cadr c)))))
                (ls (wrap (caddr c) 27 1300))
                (n (length ls))
                (y0 (- 846 (* 36 (- n 1)))))
           (fade a
             (box 110 (- y0 30) 1380 (+ 58 (* 36 (- n 1))) 16 "rgba(7,11,23,0.82)" LINE 1)
             (let loop ((ls ls) (y y0))
               (unless (null? ls)
                 (txt (car ls) 800 y 27 INK "center" 500)
                 (loop (cdr ls) (+ y 36))))))))
     caps))

  (define (draw-frame g)
    (let* ((i (scene-at g)) (sc (vector-ref reel i))
           (t (- g (vector-ref starts i))) (dur (car sc))
           (a (min (ramp t 0 0.45) (if (= i (- nscenes 1)) 1 (- 1 (ramp t (- dur 0.45) dur))))))
      (reset-cache!)
      (set! cur-a 1.0)
      (js-set! ctx "globalAlpha" 1)
      (let ((cw (js->number (js-get cv "width"))))
        (js-method ctx "setTransform" (/ cw W) 0 0 (/ cw W) 0 0))
      (js-set! ctx "textBaseline" "middle")
      (js-set! ctx "lineCap" "round")
      (js-set! ctx "lineJoin" "round")
      (js-method ctx "drawImage" bg 0 0 W H)
      (fade a
        (unless (string=? (vector-ref kickers i) "")
          (fade (ro t 0.1 0.8)
            (mtxt (vector-ref kickers i) 80 70 16 AZURE "left" 700)
            (txt (vector-ref titles i) 80 112 40 INK "left" 700)))
        ((cadr sc) t)
        (draw-caption (caddr sc) t))))

  ;; ---------------------------------------------------------------
  ;; the player
  (define clock 0.0)
  (define playing #t)
  (define last-ts #f)
  (define shown-scene -1)
  (define shown-sec -1)
  (define play-btn (get-element-by-id "play"))
  (define fill-el (get-element-by-id "fill"))
  (define time-el (get-element-by-id "clock"))
  (define track (get-element-by-id "track"))

  (define (mmss s)
    (let ((s (int s)))
      (string-append (number->string (quotient s 60)) ":"
                     (if (< (mod s 60) 10) "0" "")
                     (number->string (mod s 60)))))

  (define (set-playing! on)
    (set! playing on)
    (set-text! play-btn (cond (on "❚❚") ((>= clock total) "↺") (else "▶")))
    (js-method play-btn "setAttribute" "aria-label" (if on "Pause" "Play")))

  (define (seek! g)
    (set! clock (max 0 (min g total))))

  (define (sync-ui!)
    (let ((i (scene-at clock)) (sec (int clock)))
      (unless (= i shown-scene)
        (when (>= shown-scene 0)
          (js-method (js-get (btn shown-scene) "classList") "remove" "on"))
        (js-method (js-get (btn i) "classList") "add" "on")
        (set! shown-scene i))
      (unless (= sec shown-sec)
        (set! shown-sec sec)
        (set-text! time-el (string-append (mmss clock) " / " (mmss total))))
      (js-set! (js-get fill-el "style") "width"
               (string-append (number->string (/ (int (* 1000 (/ clock total))) 10.0)) "%"))))

  (define (fit-canvas!)
    (let* ((dpr (min 2 (js->number (js-get (js-global) "devicePixelRatio"))))
           (cw (int (* dpr (js->number (js-get cv "clientWidth")))))
           (cur (js->number (js-get cv "width"))))
      (when (and (> cw 0) (not (= cw cur)))
        (js-set! cv "width" cw)
        (js-set! cv "height" (int (* cw (/ 9 16)))))))

  (define raf #f)
  (define (tick ts)
    (let ((now (js->number ts)))
      (when (and playing last-ts)
        (seek! (+ clock (min 0.1 (/ (- now last-ts) 1000.0))))
        (when (>= clock total) (set-playing! #f)))
      (set! last-ts now)
      (fit-canvas!)
      (draw-frame (min clock (- total 0.001)))
      (sync-ui!)
      (js-method (js-global) "requestAnimationFrame" raf)
      (js-undefined)))
  (set! raf (->js tick))

  (define (toggle!)
    (if playing
        (set-playing! #f)
        (begin (when (>= clock total) (seek! 0)) (set-playing! #t))))
  (define (jump! d)
    (let ((i (max 0 (min (- nscenes 1) (+ (scene-at clock) d)))))
      (seek! (+ (vector-ref starts i) 0.001))))

  (add-event-listener! play-btn "click" (lambda (e) (toggle!) (js-undefined)))
  (add-event-listener! cv "click" (lambda (e) (toggle!) (js-undefined)))
  (add-event-listener! track "click"
    (lambda (e)
      (let ((r (js-method track "getBoundingClientRect")))
        (seek! (* total (/ (- (js->number (js-get e "clientX")) (js->number (js-get r "left")))
                           (js->number (js-get r "width"))))))
      (js-undefined)))
  (do ((i 0 (+ i 1))) ((= i (min nscenes (js->number (js-get buttons "length")))))
    (let ((k i))
      (add-event-listener! (btn k) "click"
        (lambda (e) (seek! (+ (vector-ref starts k) 0.001)) (set-playing! #t) (js-undefined)))))
  (add-event-listener! (document) "keydown"
    (lambda (e)
      (let ((k (js->string (js-get e "key")))
            (tag (js->string (js-get (js-get e "target") "tagName"))))
        (cond ((and (string=? k " ") (not (string=? tag "BUTTON")))
               (js-method e "preventDefault") (toggle!))
              ((string=? k "ArrowRight") (jump! 1))
              ((string=? k "ArrowLeft") (jump! -1))))
      (js-undefined)))

  ;; ?t=SECONDS opens paused on that frame; reduced motion starts paused
  (let* ((q (js->string (js-get (js-get (js-global) "location") "search")))
         (n (string-length q)))
    (cond
     ((and (> n 3) (string=? (substring q 0 3) "?t="))
      (seek! (let ((v (string->number (substring q 3 n)))) (if v v 0)))
      (set-playing! #f))
     ((js-truthy? (js-get (js-method (js-global) "matchMedia"
                                     "(prefers-reduced-motion: reduce)")
                          "matches"))
      (seek! 2.5)
      (set-playing! #f))
     (else (set-playing! #t))))
  (js-method (js-get (js-get (document) "body") "classList") "add" "live")
  (js-method (js-global) "requestAnimationFrame" raf))

;; ---- the page ----------------------------------------------------------
(define page-css
  '((":root" (--bg "#070b17") (--panel "#111831") (--line "#253157")
             (--ink "#e8ecf8") (--dim "#8e98bd") (--azure "#4f8ff7")
             (--mono "ui-monospace, \"SF Mono\", Menlo, Consolas, monospace"))
    ("*" (box-sizing border-box))
    (body (margin 0) (background (var bg)) (color (var ink))
          (font-family "Inter, system-ui, -apple-system, \"Segoe UI\", sans-serif")
          (line-height (dec 1 55)))
    (a (color (var azure)) (text-decoration none))
    (".top" (max-width (px 1280)) (margin 0 auto) (padding (px 18) (px 16) (px 10))
            (display flex) (align-items baseline) (gap (px 14)) (flex-wrap wrap))
    (".brand" (font-family "\"Times New Roman\", Times, serif") (font-size (px 24))
              (color (var azure)))
    (".top h1" (font-size (px 17)) (font-weight 500) (margin 0) (color (var dim)))
    (".player" (max-width (px 1280)) (margin 0 auto) (padding 0 (px 16)))
    ("#stage" (display none) (width (pct 100)) (aspect-ratio "16 / 9")
              (border-radius (px 14)) (background "#0a0f1f") (cursor pointer)
              (box-shadow "0 20px 60px rgba(0,0,0,.45)")
              (border (px 1) solid (var line)))
    (".live #stage" (display block))
    (".bar" (display none) (align-items center) (gap (px 14)) (margin (px 12) 0 (px 6)))
    (".live .bar" (display flex))
    ("#play" (width (px 44)) (height (px 36)) (border-radius (px 8))
             (border (px 1) solid (var line)) (background (var panel)) (color (var ink))
             (font-size (px 15)) (cursor pointer))
    ("#track" (flex 1) (height (px 8)) (border-radius (px 4)) (background (var panel))
              (border (px 1) solid (var line)) (cursor pointer) (overflow hidden))
    ("#fill" (height (pct 100)) (width 0) (background (var azure)))
    ("#clock" (font-family (var mono)) (font-size (px 13)) (color (var dim))
              (min-width (px 92)) (text-align right))
    (".chapters" (list-style none) (padding 0) (margin (px 14) 0 (px 40))
                 (display grid) (grid-template-columns "repeat(auto-fill, minmax(236px, 1fr))")
                 (gap (px 10)))
    (".ch" (width (pct 100)) (height (pct 100)) (text-align left) (padding (px 10) (px 12))
           (border-radius (px 10)) (border (px 1) solid (var line)) (background (var panel))
           (color (var ink)) (font "inherit") (cursor pointer))
    (".ch:hover" (border-color (var azure)))
    (".ch.on" (border-color (var azure)) (background "#16224a"))
    (".ch .k" (display block) (font-family (var mono)) (font-size (px 11))
              (color (var azure)) (letter-spacing (px 1)))
    (".ch .t" (display block) (font-weight 600) (font-size (px 15)))
    (".ch .s" (display none) (color (var dim)) (font-size (px 13)) (margin-top (px 4)))
    ("body:not(.live) .ch .s" (display block))
    ("body:not(.live) .ch" (cursor default))
    (".note" (max-width (px 1280)) (margin 0 auto (px 40)) (padding 0 (px 16))
             (color (var dim)) (font-size (px 13)))
    ("kbd" (font-family (var mono)) (border (px 1) solid (var line))
           (border-radius (px 4)) (padding 0 (px 5)))))

(define (chapter-item c)
  `(li (button (@ (class "ch") (data-k ,(car c)) (data-t ,(cadr c)))
         (span (@ (class "k")) ,(if (string=? (car c) "") "·" (car c)))
         (span (@ (class "t")) ,(cadr c))
         (span (@ (class "s")) ,(caddr c)))))

(write-file "intro.html"
  (html->document
   `(html (@ (lang "en"))
      (head
       (meta (@ (charset "utf-8")))
       (meta (@ (name "viewport") (content "width=device-width, initial-scale=1")))
       (link (@ (rel "icon") (type "image/svg+xml") (href "favicon.svg")))
       (title "Beyond Files")
       (meta (@ (name "description")
                (content "An animated introduction: why files fail as the substrate for multi-agent systems, and the block graph that replaces them.")))
       (style ,(css->string page-css)))
      (body
       (div (@ (class "top"))
         (a (@ (class "brand") (href "index.html")) "Goeteia")
         (h1 "Beyond Files — why multi-agent systems need blocks, not files"))
       (div (@ (class "player"))
         (canvas (@ (id "stage") (width "1600") (height "900")
                    (aria-label "Animated introduction; the chapter list below is its transcript")))
         (div (@ (class "bar"))
           (button (@ (id "play") (aria-label "Pause")) "❚❚")
           (div (@ (id "track")) (div (@ (id "fill"))))
           (span (@ (id "clock")) "0:00"))
         (ol (@ (class "chapters")) ,@(map chapter-item chapters)))
       (p (@ (class "note"))
          (kbd "space") " play / pause · " (kbd "←") " " (kbd "→") " chapters. "
          "Every frame is drawn by Scheme compiled to WebAssembly by Goeteia, "
          "with a JavaScript twin generated from the same source — see "
          (a (@ (href "https://github.com/guenchi/Goeteia/blob/website/site/intro.ss"))
             "site/intro.ss") ".")
       ,(raw film)))))
